const assert=require('node:assert/strict'),{worker}=require('./worker-harness'),{fakeStorageArea}=require('./fake-chrome');
const plain=x=>JSON.parse(JSON.stringify(x)),tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
  const w=worker();await w.ready();await w.context.AE.preferencesReady;
  assert.equal((await w.send({type:'AE_PREFERENCES'},null)).preferences.autoArchive,true);
  assert.equal((await w.send({type:'AE_SET_PREFERENCES',preferences:{autoArchive:false}},null)).ok,true);assert.equal(w.context.autoArchiveEnabled,false);assert.equal((await w.context.runTurnSync('turn','default')).paused,true);
  const reboot=worker({local:w.local});await reboot.ready();await reboot.context.AE.preferencesReady;assert.equal(reboot.context.autoArchiveEnabled,false);
  assert.equal((await w.send({type:'AE_SET_PREFERENCES',preferences:{autoArchive:true}},{id:1,url:'https://arena.ai/c/a'})).ok,false);assert.equal(w.context.autoArchiveEnabled,false);
  let parses=0;const original=w.context.AE.parseEvaluationStream;w.context.AE.parseEvaluationStream=(...args)=>{parses++;return original(...args);};
  const s=w.context.freshState('c:cache'),raw='a0:{"d":"Hello"}\nad:{"finishReason":"stop"}';
  const p=w.context.AE.parseCachedEvaluation(s,'round',raw,null);assert.equal(w.context.AE.parseCachedEvaluation(s,'round',raw,null),p);assert.equal(parses,1);
  w.context.AE.parseCachedEvaluation(s,'round',raw+'\n',null);assert.equal(parses,2);w.context.AE.parseCachedEvaluation(s,'round',raw+'\n',{mode:'direct'});assert.equal(parses,3);
  w.context.store.sessions['c:cache']=s;w.context.store.activeKey='default';s.messages=[{role:'user',content:[{type:'text',text:'Target only'}]}];
  const out=w.context.buildExport('full_history',null,s);assert.equal(out.payload.session.conversation_key,'c:cache');assert.equal(w.context.store.activeKey,'default');
  s.messages=[['user','Old prompt'],['assistant','Old answer'],['user','Current prompt'],['assistant','Current answer']].map(([role,text])=>({role,content:[{type:'text',text}]}));
  s.streamSamples=[{sample:'Old prompt'}];s.capturedRequests=[{request_id:'old',body:'Old prompt'},{request_id:'new',body:'Current prompt'}];
  s.requestAttempts=[{request_id:'old',mode:'agent'},{request_id:'new',mode:'agent'}];
  const lastJson=await w.send({type:'AE_EXPORT',sessionKey:'c:cache',mode:'last_message'},null);
  assert.equal(lastJson.ok,true);assert.ok(!lastJson.json.includes('Old prompt'));assert.ok(!lastJson.json.includes('Old answer'));assert.ok(lastJson.json.includes('Current answer'));
  const markdown=await w.send({type:'AE_EXPORT',sessionKey:'c:cache',mode:'last_message',format:'markdown'},null);
  assert.equal(markdown.ok,true);assert.match(markdown.filename,/\.md$/);assert.ok(markdown.text.includes('Current answer'));assert.ok(!markdown.text.includes('Old prompt'));
  const clean=w.context.AE.redactSecretText('Bearer abc_DEF_0123456789 sk-proj-abcdefghijklmnopqrstuvwxyz token=eyJabcdefghijk.abc_def.abcdefgh');
  assert.ok(!clean.includes('abc_DEF')&&!clean.includes('sk-proj-')&&!clean.includes('eyJ'));assert.equal(w.context.AE.redactSecretText(clean),clean);
  const diag=plain((await w.send({type:'AE_DIAGNOSTICS'},null)).diagnostics);assert.ok(!JSON.stringify(diag).includes('Target only'));assert.ok(!JSON.stringify(diag).includes('c:cache'));
  let release;const commits=[],storage=fakeStorageArea();storage.set=obj=>new Promise(resolve=>{commits.push(plain(obj));release=resolve;});
  const q=worker({session:storage});await q.ready();q.context.store.sessions.default.session.title='first';const one=q.context.flushSave();await tick();
  q.context.store.sessions.default.session.title='second';const two=q.context.flushSave();await tick();assert.equal(commits.length,1);release();await one;await tick();assert.equal(commits.length,2);
  assert.equal(commits[0].ae_store_v2.sessions.default.session.title,'first');assert.equal(commits[1].ae_store_v2.sessions.default.session.title,'second');release();await two;
  console.log('Preferences, restart, authorization, parse cache, explicit session, redaction, diagnostics and serialized persistence passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
