const assert=require('node:assert/strict'),{uiFixture}=require('./ui-harness'),view=require('../src/ui-model');
const entries=Array.from({length:25},(_,i)=>({key:'c:'+i,title:i===0?'Unique weather project':'Conversation '+i,mode:i%2?'battle':'agent',subtype:'text',turns:i,models:i%2?['Alpha','Beta']:[],rel:'agent/folder-'+i,url:'https://arena.ai/c/'+i,updated_at:'2026-09-'+String(i+1).padStart(2,'0'),completeness:'full'}));
(async()=>{
  const f=await uiFixture('options',{entries});assert.equal(f.document.getElementById('library-rows').children.length,20);await f.fire('page-next');assert.equal(f.document.getElementById('library-rows').children.length,5);
  f.document.getElementById('library-search').value='UNIQUE weather';await f.fire('library-search','input');assert.equal(f.document.getElementById('library-rows').children.length,1);assert.equal(f.document.getElementById('page-label').textContent,'Page 1 / 1');
  const row=f.document.getElementById('library-rows').children[0];await row.children[4].children[0].children[0].fire();await f.tick();assert.equal(f.last('AE_OPEN_ARCHIVED_FOLDER').key,'c:0');
  await row.children[0].children[0].fire();assert.equal(f.opened.at(-1).url,'https://arena.ai/c/0');
  f.document.getElementById('library-search').value='Nothing matches this';await f.fire('library-search','input');assert.ok(!f.document.getElementById('library-empty').classList.contains('hidden'));await f.fire('empty-reset');assert.equal(f.document.getElementById('library-rows').children.length,20);
  assert.equal(view.filterEntries(entries,'Alpha','agent','recent').length,0);assert.equal(view.filterEntries(entries,'Alpha','battle','recent').length,12);assert.equal(view.filterEntries(entries,'','all','turns')[0].turns,24);
  assert.equal(view.arenaUrl('https://arena.ai.attacker.test/c/a'),false);assert.equal(view.backupLabel({ok:true,connected:true,enabled:true,pending:0}),'GitHub backup ready');assert.equal(view.backupLabel({ok:true,connected:true,enabled:true,pending:0,lastSuccess:'today'}),'Backed up to GitHub');
  await f.fire('btn-diagnostics');assert.equal(f.last('AE_SAVE_TEXT').filename,'arena-exporter-diagnostics.json');
  const permissionRequests=[];
  const chromeAlias=await uiFixture('options',{setup:c=>{c.browser=c.chrome;c.chrome.permissions.request=(p,cb)=>{assert.ok(!('data_collection' in p),'Chrome must never receive Firefox permission fields');permissionRequests.push(p);cb(true);};}});
  assert.equal(chromeAlias.document.getElementById('chk-silent').disabled,false,'The Chrome browser alias must not disable quiet downloads');
  await chromeAlias.fire('github-form','submit');assert.ok(chromeAlias.last('AE_GITHUB_CONFIGURE'));assert.equal(permissionRequests.length,1);
  const firefoxRequests=[];
  const firefox=await uiFixture('options',{setup:c=>{c.browser={runtime:{getBrowserInfo:async()=>({name:'Firefox'})},permissions:{request:async p=>{firefoxRequests.push(p);return false;}}};}});
  await firefox.fire('github-form','submit');assert.equal(firefoxRequests[0].data_collection.length,3);assert.equal(firefox.last('AE_GITHUB_CONFIGURE'),undefined);
  const thrown=await uiFixture('options',{setup:c=>{c.chrome.permissions.request=()=>{throw new Error('Permission request failed');};}});
  await thrown.fire('github-form','submit');assert.equal(thrown.document.getElementById('progress-msg').textContent,'Permission request failed');assert.equal(thrown.document.getElementById('github-connect').disabled,false);
  const locked=await uiFixture('options',{respond:m=>{
    if(m.type==='AE_PREFERENCES')return {ok:true,preferences:{autoArchive:true,archiveEncryption:{enabled:true}},encryption:{enabled:true,unlocked:false}};
    if(m.type==='AE_SET_ARCHIVE_ENCRYPTION')return {ok:true,encryption:{enabled:false,unlocked:false},preferences:{autoArchive:true,archiveEncryption:{enabled:false}}};
    return undefined;
  }});
  await locked.tick();
  const encryptionToggle=locked.document.getElementById('archive-encryption');
  encryptionToggle.checked=false;
  await encryptionToggle.fire('change');
  locked.document.getElementById('encryption-password').value='current password';
  locked.document.getElementById('encryption-confirm').value='current password';
  await locked.fire('btn-encryption-save');
  assert.equal(locked.last('AE_SET_ARCHIVE_ENCRYPTION').enabled,false,'disabling a locked archive must not take the unlock path');
  console.log('Library search, filtering, pagination, folder/Arena actions, empty states, backup labels, diagnostics, and locked-encryption disable flow passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
