// Generated by tools/build-release.mjs. Edit the source modules.
(function () {
// Source: src/lib/schema.js
/* Shared constants for Arena Agent Exporter.
 * Loaded by both the content-script world (as a classic script) and the
 * service worker (via importScripts). Everything hangs off the global `AE`. */
var AE = AE || {};

AE.SCHEMA_VERSION = "2.1";

/* postMessage bridge type between MAIN-world interceptor and ISOLATED content script */
AE.MSG_NS = "__ARENA_EXPORTER_EVT__";

/* Canonical block types used in the export schema */
AE.BLOCK_TYPES = [
  "thinking",    // chain-of-thought text
  "text",        // visible message text (markdown)
  "tool_call",   // tool invocation with arguments
  "tool_result", // output of a tool invocation
  "command",     // shell/terminal command + output
  "action",      // higher-level agent action (create_file, navigate, ...)
  "artifact"     // produced files / images / reports
];

AE.ROLES = ["user", "assistant", "system", "tool"];

/* Canonical battle-vote choices. A/B identify a single preferred lane;
 * both_good and neither_good preserve the two non-singular ballot outcomes. */
AE.BATTLE_VOTE_CHOICES = ["A", "B", "both_good", "neither_good"];

AE.isPlaceholderModel = function (name) {
  var t = String(name == null ? "" : name).replace(/\s+/g, " ").trim();
  if (!t) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(t)) return true;
  return /^(?:response|model|assistant|lane|player|option)\s*[ab](?:\s+[ab]\s+is\s+better)?$/i.test(t);
};

;
// Source: src/lib/privacy.js
/* Credential filtering shared by capture, history and export. Never sample or
 * truncate an unfiltered body: that can turn valid JSON into an unredactable fragment. */
var AE = AE || {};
(function () {
  "use strict";
  var SECRET_NAMES = /^(?:recaptcha.*|grecaptcha.*|captcha.*|authorization|proxyauthorization|cookie|setcookie|apikey|secret|clientsecret|password|passwd|token|accesstoken|publicaccesstoken|refreshtoken|idtoken|sessiontoken|authtoken|bearertoken|jwt|credentials|privatekey)$/i;
  function secretName(name) { return SECRET_NAMES.test(String(name || "").replace(/[^a-z0-9]/gi, "")); }
  var FIELD = "(?:recaptcha[a-z0-9_-]*|g-recaptcha[a-z0-9_-]*|captcha[a-z0-9_-]*|authorization|proxy-authorization|cookie|set-cookie|api[-_]?key|client[-_]?secret|secret|password|passwd|(?:public[-_]?)?access[-_]?token|refresh[-_]?token|id[-_]?token|session[-_]?token|auth[-_]?token|bearer[-_]?token|token|jwt|credentials|private[-_]?key)";
  var FIELD_VALUE = new RegExp("((?:[\\\"']?" + FIELD + "[\\\"']?)\\s*[:=]\\s*)(?:\\\"(?:\\\\.|[^\\\"\\\\])*(?:\\\"|$)|'(?:\\\\.|[^'\\\\])*(?:'|$)|[^&\\s,;}\\]]+)", "gi");
  var QUERY_SECRET = new RegExp("([?&]" + FIELD + "=)[^&#\\s]*", "gi");
  AE.redactSecretText = function (text) {
    return String(text || "")
      .replace(/\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]*)?/g, "[REDACTED_JWT]")
      .replace(/\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+\/_-]+=*/gi, "[REDACTED_AUTH]")
      .replace(/\bsk-[A-Za-z0-9_-]{16,}/g, "[REDACTED_KEY]")
      .replace(/^((?:proxy-)?authorization|cookie|set-cookie)(\s*:\s*)[^\r\n]*/gim, "$1$2[REDACTED]")
      .replace(QUERY_SECRET, "$1[REDACTED]")
      .replace(FIELD_VALUE, '$1"[REDACTED]"');
  };
  AE.scrubSecrets = function (value) {
    function walk(v, depth) {
      if (typeof v === "string") {
        // Trigger records and websocket frames often contain JSON inside JSON.
        if (depth < 12 && /^[\s]*[\[{]/.test(v)) {
          try { return JSON.stringify(walk(JSON.parse(v), depth + 1)); } catch (e) { /* raw or truncated frame */ }
        }
        return AE.redactSecretText(v);
      }
      if (Array.isArray(v)) {
        if (v.length === 2 && typeof v[0] === "string" && secretName(v[0])) return [v[0], "[REDACTED]"];
        return v.map(function (item) { return walk(item, depth + 1); });
      }
      if (!v || typeof v !== "object") return v;
      var out = {};
      Object.keys(v).forEach(function (key) {
        if (secretName(key) || key === "__proto__" || key === "constructor" || key === "prototype") return;
        out[key] = walk(v[key], depth + 1);
      });
      return out;
    }
    return walk(value, 0);
  };
  AE.safeTransportHeaders = function (headers) {
    var out = {};
    ["x-session-settled", "x-stream-version", "x-arena-chat-id"].forEach(function (name) {
      var value = null;
      if (headers && typeof headers.get === "function") value = headers.get(name);
      else if (Array.isArray(headers)) headers.forEach(function (pair) {
        if (pair && String(pair[0]).toLowerCase() === name) value = pair[1];
      });
      else if (headers) Object.keys(headers).forEach(function (key) {
        if (key.toLowerCase() === name) value = headers[key];
      });
      if (value != null) out[name] = AE.redactSecretText(value).slice(0, 200);
    });
    return out;
  };
})();

;
// Source: src/lib/page-data.js
/* Read public page hydration data without executing scripts or depending on
 * bundle module ids. Catalog labels describe a selection, not a hidden Agent model. */
var AE = AE || {};
(function () {
  "use strict";
  AE.catalogModelLabel = function (row) {
    if (!row || typeof row !== "object") return null;
    var values = [row.publicName, row.displayName, row.name];
    for (var i = 0; i < values.length; i++) {
      if (typeof values[i] === "string" && values[i] && !AE.isPlaceholderModel(values[i])) return values[i];
    }
    return null;
  };
  AE.catalogModel = function (catalog, id) {
    if (!id || !catalog || !Array.isArray(catalog.models)) return null;
    return catalog.models.find(function (row) { return row.id === id; }) || null;
  };
  AE.cleanModelCatalog = function (rows, url) {
    var seen = {};
    var fields = ["id", "name", "publicName", "displayName", "organization", "provider", "userSelectable", "rank", "rankByModality"];
    var models = [];
    (Array.isArray(rows) ? rows : []).slice(0, 4000).forEach(function (row) {
      if (!row || typeof row.id !== "string" || row.id.length > 160 || seen[row.id]) return;
      seen[row.id] = true;
      var clean = {};
      fields.forEach(function (field) {
        var value = row[field];
        if (value == null) return;
        if (typeof value === "string") clean[field] = value.slice(0, 300);
        else if (typeof value === "number" || typeof value === "boolean") clean[field] = value;
        else if (typeof value === "object" && JSON.stringify(value).length < 3000) clean[field] = value;
      });
      models.push(clean);
    });
    return { source_url: url || null, captured_at: new Date().toISOString(), models: models };
  };
  AE.assistantMetadata = function (message) {
    var source = Object.assign({}, message || {}, (message && (message.metadata || message.messageMetadata)) || {});
    var out = {};
    ["nodeId", "manifestNodeId", "pending", "requiresReview", "feedback"].forEach(function (key) {
      if (Object.prototype.hasOwnProperty.call(source, key)) out[key] = source[key];
    });
    return AE.scrubSecrets(out);
  };
  AE.transcriptMetadata = function (transcript) {
    var out = {};
    ["pagination", "transcriptReadStrategy", "productMode", "feedbackType", "customFeedbackArm"].forEach(function (key) {
      if (Object.prototype.hasOwnProperty.call(transcript || {}, key)) out[key] = transcript[key];
    });
    if (transcript && transcript.session) out.session = AE.scrubSecrets(transcript.session);
    return AE.scrubSecrets(out);
  };
  AE.pageDataFromObjects = function (objects, url, references) {
    var result = { catalog: null, transcript: null };
    var visits = 0;
    var visited = new Set();
    function resolve(value, depth) {
      if (depth > 12) return value;
      if (typeof value === "string" && /^\$[a-f0-9]+$/i.test(value) && references) {
        var ref = references[value.slice(1)];
        if (ref !== undefined && ref !== value) return resolve(ref, depth + 1);
      }
      if (Array.isArray(value)) return value.map(function (v) { return resolve(v, depth + 1); });
      return value;
    }
    function walk(value, depth) {
      if (++visits > 80000 || depth > 35) return;
      value = resolve(value, 0);
      if (!value || typeof value !== "object" || visited.has(value)) return;
      visited.add(value);
      if (value.initialModels) {
        var rows = resolve(value.initialModels, 0);
        if (Array.isArray(rows)) result.catalog = AE.cleanModelCatalog(rows, url);
      }
      var messages = resolve(value.messages, 0);
      if (Array.isArray(messages) && messages.some(function (m) { return m && m.role && Array.isArray(m.parts); })) {
        result.transcript = Object.assign({}, value, { messages: messages });
      }
      Object.keys(value).forEach(function (key) {
        if (key !== "initialModels" && key !== "messages") walk(value[key], depth + 1);
      });
    }
    (Array.isArray(objects) ? objects : [objects]).forEach(function (o) { walk(o, 0); });
    return result;
  };
  AE.parsePageData = function (source, url) {
    source = String(source || "").slice(0, 8 * 1024 * 1024);
    var chunks = [];
    var re = /self\.__next_f\.push\(\s*\[\s*1\s*,\s*("(?:\\.|[^"\\])*")\s*\]\s*\)/g;
    var match;
    while ((match = re.exec(source))) {
      try { chunks.push(JSON.parse(match[1])); } catch (e) { /* incomplete script */ }
    }
    var flight = chunks.length ? chunks.join("") : source;
    var objects = [], references = {};
    flight.split(/\r?\n/).forEach(function (line) {
      var row = /^([a-f0-9]+):(?:J)?([\[{].*)$/i.exec(line);
      if (!row) return;
      try {
        references[row[1]] = JSON.parse(row[2]);
        objects.push(references[row[1]]);
      } catch (e) { /* non-JSON Flight row or a partial stream */ }
    });
    if (!objects.length) {
      try { objects.push(JSON.parse(flight)); } catch (e) { /* HTML without hydration data */ }
    }
    return AE.pageDataFromObjects(objects, url, references);
  };
})();

;
// Source: src/lib/dom-extract.js
/* DOM-based extraction — fallback + completeness check.
 * Strategy (most robust first): data-testid/data-* attributes → ARIA
 * roles/labels → class heuristics. Before scraping, collapsed disclosure
 * controls (thinking panels, tool-call accordions) are expanded so the full
 * chain-of-thought is recoverable from the rendered page. */
var AE = AE || {};
AE.dom = {};

(function () {
  "use strict";

  var EXPAND_LABEL_RE = /(show|expand|view|reveal)[\s\S]{0,20}(thinking|reasoning|steps?|details?|tool|actions?|process)|^(thinking|show more)$/i;

  /* ---------- expand-before-scrape ---------- */

  AE.dom.expandCollapsed = function () {
    var clicked = 0;
    try {
      document.querySelectorAll("details:not([open])").forEach(function (d) {
        try { d.open = true; clicked++; } catch (e) {}
      });
      var nodes = document.querySelectorAll('button, [role="button"], summary');
      nodes.forEach(function (b) {
        var label = ((b.getAttribute("aria-label") || "") + " " + (b.textContent || "")).trim().replace(/\s+/g, " ");
        if (label && label.length < 60 && EXPAND_LABEL_RE.test(label)) {
          try { b.click(); clicked++; } catch (e) {}
        }
      });
      // arena.ai: collapsed file-operation rows inside the chat log.
      var log = document.querySelector('[role="log"]');
      if (log) {
        log.querySelectorAll('[role="button"][aria-expanded="false"][aria-label="Expand"]').forEach(function (b) {
          try { b.click(); clicked++; } catch (e) {}
        });

        /* Current arena.ai code-battle rows use Radix disclosures.  Their
         * buttons have an aria-controls/id pair but no aria-label="Expand";
         * the old selector therefore left every file body (the actual tool
         * arguments) unmounted.  Restrict this pass to labels understood by
         * the modern tool mapper so ballot/navigation controls are untouched. */
        log.querySelectorAll('button[aria-expanded="false"][aria-controls]').forEach(function (b) {
          var label = compactText(b.innerText || b.textContent || "");
          if (!toolNameFromModernLabel(label)) return;
          try { b.click(); clicked++; } catch (e) {}
        });
      } else {
        /* Keep the fallback useful on layouts that omit role=log. */
        document.querySelectorAll('button[aria-expanded="false"][aria-controls]').forEach(function (b) {
          var label = compactText(b.innerText || b.textContent || "");
          if (!toolNameFromModernLabel(label)) return;
          try { b.click(); clicked++; } catch (e) {}
        });
      }
    } catch (e) { /* ignore */ }
    // Give the app a beat to render expanded content before scraping.
    return new Promise(function (resolve) {
      var delay = clicked ? Math.min(2500, 500 + Math.ceil(clicked / 20) * 100) : 50;
      setTimeout(function () { resolve(clicked); }, delay);
    });
  };

  /* ---------- message container discovery ---------- */

  var CONTAINER_SELECTORS = [
    '[data-testid*="message" i]',
    '[data-testid*="turn" i]',
    '[data-testid*="chat-item" i]',
    '[data-message-id]',
    '[data-role]',
    '[id^="message-" i]'
  ];
  var FALLBACK_SELECTOR = '[class*="message" i]';

  function contains(root, el) {
    return root !== el && root.contains(el);
  }

  function findContainers() {
    var found = [];
    for (var i = 0; i < CONTAINER_SELECTORS.length; i++) {
      try { found = Array.from(document.querySelectorAll(CONTAINER_SELECTORS[i])); } catch (e) {}
      if (found.length >= 2) break;
    }
    if (found.length < 2) {
      try { found = Array.from(document.querySelectorAll(FALLBACK_SELECTOR)); } catch (e) {}
    }
    // Keep only elements with real content, drop ones nested inside another candidate.
    var candidates = found.filter(function (el) {
      return el && ((el.innerText || "").trim().length > 0 || el.querySelector("pre"));
    });
    return candidates.filter(function (el) {
      return !candidates.some(function (other) { return contains(other, el); });
    });
  }

  /* ---------- role inference ---------- */

  function inferRole(el, index, total) {
    var sig = [
      el.getAttribute("data-role") || "",
      el.getAttribute("data-testid") || "",
      el.getAttribute("class") || "",
      el.getAttribute("aria-label") || ""
    ].join(" ").toLowerCase();
    if (/(^|[\s_-])(user|human|prompt)([\s_-]|$)/.test(sig)) return "user";
    if (/(^|[\s_-])(assistant|agent|model|bot|ai)([\s_-]|$)/.test(sig)) return "assistant";
    // Weak positional heuristic; export meta marks DOM-sourced data.
    return index % 2 === 0 ? "user" : "assistant";
  }

  /* ---------- structured regions inside a container ---------- */

  var THINKING_SELECTORS = [
    '[data-testid*="thinking" i]',
    '[class*="thinking" i]',
    '[class*="reasoning" i]',
    '[aria-label*="thinking" i]'
  ];
  var TOOL_SELECTORS = [
    '[data-testid*="tool" i]',
    '[class*="tool-call" i]',
    '[class*="toolcall" i]',
    '[class*="tool_use" i]'
  ];
  var COMMAND_SELECTORS = [
    '[data-testid*="command" i]',
    '[class*="terminal" i]',
    '[class*="console-output" i]',
    '[class*="shell" i]'
  ];
  var ARTIFACT_SELECTORS = [
    '[data-testid*="artifact" i]',
    '[class*="artifact" i]',
    '[class*="preview-card" i]'
  ];

  function firstMatch(root, selectors) {
    for (var i = 0; i < selectors.length; i++) {
      try {
        var els = root.querySelectorAll(selectors[i]);
        if (els.length) return Array.from(els);
      } catch (e) {}
    }
    return [];
  }

  function clip(text, n) {
    text = (text || "").trim().replace(/\s+/g, " ");
    return text.length > n ? text.slice(0, n) + "…" : text;
  }

  /* ---------- arena.ai-specific extraction (from live DOM recon) ----------
   * Structure: [role="log"] → wrapper div → per-turn divs.
   *   user turns:      div[class*="items-end"][class*="flex-col"] bubbles
   *   assistant turns: div[class*="rounded-xl"][class*="overflow-hidden"] cards
   *     containing tool/file-op rows ([role=button][aria-label="Expand"]),
   *     artifact cards (class*=artifact with iframe srcdoc previews), and
   *     .prose response text. */

  function byDocOrder(a, b) {
    if (a === b) return 0;
    var rel = a.compareDocumentPosition(b);
    if (rel & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
    if (rel & Node.DOCUMENT_POSITION_PRECEDING) return 1;
    return 0;
  }

  function toArray(list) { return Array.prototype.slice.call(list); }

  function extractUserContent(el) {
    var text = "";
    toArray(el.querySelectorAll(".prose")).forEach(function (p) {
      var t = (p.innerText || "").trim();
      if (t) text += (text ? "\n\n" : "") + t;
    });
    if (!text) text = (el.innerText || "").trim();
    if (!text) return [];
    return [{ type: "text", text: text, format: "markdown", source: "dom" }];
  }

  function extractAssistantContent(el) {
    var content = [];
    var seenToolRows = [];

    function addModernToolRow(row) {
      if (!row || seenToolRows.indexOf(row) !== -1) return;
      var label = compactText(row.innerText || row.textContent || "");
      var toolName = toolNameFromModernLabel(label);
      if (!toolName) return;
      seenToolRows.push(row);
      var path = modernPathFromLabel(label);
      var detail = modernDisclosureDetail(row);
      var isEdit = /^(?:edited|updated|patched)\b/i.test(label);
      var args = path ? { path: path } : null;
      var block = {
        type: "tool_call",
        tool_name: toolName,
        call_id: null,
        arguments: args,
        summary: clip(label, 400),
        status: "success",
        source: "dom"
      };
      if (detail) {
        block.detail_source = detail.source;
        if (detail.code) {
          if (!args) args = {};
          if (isEdit) args.patch = detail.code;
          else args.content = detail.code;
          block.arguments = args;
          if (isEdit && detail.diff) block.diff = detail.diff;
          if (!isEdit && toolName !== "create_file") block.output = detail.code;
        } else if (detail.text) {
          block.output = detail.text;
        }
      }
      content.push(block);
    }

    // Tool / file-operation rows: "Write  cool.html  48 lines"
    toArray(el.querySelectorAll('[role="button"][aria-label="Expand"]')).forEach(function (row) {
      if (toolNameFromModernLabel(compactText(row.innerText || row.textContent || ""))) {
        addModernToolRow(row);
        return;
      }
      var verbEl = row.querySelector('span[class*="text-text-secondary"]');
      var fileEl = row.querySelector('span[class*="font-mono"]');
      var verb = verbEl ? verbEl.innerText.trim() : "";
      var file = fileEl ? fileEl.innerText.trim() : "";
      var summary = clip(row.innerText, 400);
      if (!summary) return;
      seenToolRows.push(row);
      var oldDetail = modernDisclosureDetail(row);
      var oldArgs = file ? { file: file } : null;
      if (oldDetail && oldDetail.code) {
        if (!oldArgs) oldArgs = {};
        oldArgs.content = oldDetail.code;
      }
      content.push({
        type: "tool_call",
        tool_name: verb || "unknown",
        call_id: null,
        arguments: oldArgs,
        summary: summary,
        status: "success",
        detail_source: oldDetail ? oldDetail.source : undefined,
        output: oldDetail && !oldDetail.code ? oldDetail.text : undefined,
        source: "dom"
      });
    });

    /* Modern Radix rows have an aria-controls target and a normal button role,
     * but no aria-label="Expand". They are the rows that contain the actual
     * create/edit/read payloads in today's Arena UI. */
    toArray(el.querySelectorAll('button[aria-expanded][aria-controls], [role="button"][aria-expanded][aria-controls]'))
      .forEach(addModernToolRow);

    // Artifact cards (title + type badge + iframe preview holding file source)
    toArray(el.querySelectorAll('div[role="button"][class*="artifact"]')).forEach(function (card) {
      var titleEl = card.querySelector('span[class*="truncate"][class*="text-sm"]');
      var badgeEl = card.querySelector('span[class*="uppercase"]');
      var iframe = card.querySelector("iframe");
      var srcdoc = iframe ? (iframe.getAttribute("srcdoc") || "") : "";
      content.push({
        type: "artifact",
        artifact_type: badgeEl ? badgeEl.innerText.trim().toLowerCase() : "unknown",
        title: titleEl ? titleEl.innerText.trim() : null,
        content_or_url: srcdoc ? srcdoc.slice(0, 16000) : null,
        truncated: srcdoc.length > 16000,
        source: "dom"
      });
    });

    // Response prose, excluding already-captured regions
    var clone = el.cloneNode(true);
    toArray(clone.querySelectorAll('[role="button"][aria-label="Expand"], button[aria-expanded][aria-controls], [role="button"][aria-expanded][aria-controls], div[role="button"][class*="artifact"], iframe')).forEach(function (n) {
      n.remove();
    });
    var text = "";
    toArray(clone.querySelectorAll(".prose")).forEach(function (p) {
      var t = (p.innerText || "").trim();
      if (t) text += (text ? "\n\n" : "") + t;
    });
    if (text) content.push({ type: "text", text: text, format: "markdown", source: "dom" });

    return content;
  }

  function extractArenaTurns() {
    var log = document.querySelector('[role="log"]');
    if (!log) return null;
    var userEls = toArray(log.querySelectorAll('div[class*="items-end"][class*="flex-col"]'));
    var asstEls = toArray(log.querySelectorAll('div[class*="rounded-xl"][class*="overflow-hidden"]'));
    var merged = userEls.map(function (el) { return { el: el, role: "user" }; })
      .concat(asstEls.map(function (el) { return { el: el, role: "assistant" }; }));
    if (!merged.length) return null;
    merged.sort(function (a, b) { return byDocOrder(a.el, b.el); });

    var messages = [];
    merged.forEach(function (turn, i) {
      var content = turn.role === "user" ? extractUserContent(turn.el) : extractAssistantContent(turn.el);
      if (!content.length) return;
      messages.push({
        id: "dom_msg_" + i,
        turn_index: i,
        role: turn.role,
        timestamp: null,
        content: content
      });
    });
    return messages;
  }

  /* ---------- main extraction ---------- */

  AE.dom.extract = function () {
    var messages = null;
    var strategy = "arena";
    try { messages = extractArenaTurns(); } catch (e) { messages = null; }
    if (!messages || !messages.length) {
      messages = extractGenericMessages();
      strategy = "generic";
    }
    return {
      source: "dom",
      url: location.href,
      extracted_at: new Date().toISOString(),
      strategy: strategy,
      messages: messages
    };
  };

  /* Generic container heuristic — fallback for unknown layouts. */
  function extractGenericMessages() {
    var containers = findContainers();
    var messages = [];

    containers.forEach(function (el, i) {
      var role = inferRole(el, i, containers.length);
      var content = [];

      // Thinking / reasoning regions
      firstMatch(el, THINKING_SELECTORS).forEach(function (t) {
        var text = (t.innerText || "").trim();
        if (text) content.push({ type: "thinking", text: text, source: "dom" });
      });

      // Tool calls
      firstMatch(el, TOOL_SELECTORS).forEach(function (t) {
        var text = (t.innerText || "").trim();
        if (!text) return;
        content.push({
          type: "tool_call",
          tool_name: guessToolName(t),
          call_id: null,
          arguments: null,
          summary: clip(text, 800),
          status: "unknown",
          source: "dom"
        });
      });

      // Commands / terminal output
      firstMatch(el, COMMAND_SELECTORS).forEach(function (c) {
        var text = (c.innerText || "").trim();
        if (text) content.push({ type: "command", command: clip(text, 1000), source: "dom" });
      });

      // Artifacts
      firstMatch(el, ARTIFACT_SELECTORS).forEach(function (a) {
        var text = (a.innerText || "").trim();
        if (text) {
          content.push({
            type: "artifact",
            artifact_type: "unknown",
            title: clip(text, 120),
            content_or_url: null,
            source: "dom"
          });
        }
      });

      // Visible text: clone the node and strip structured regions so prose
      // isn't duplicated alongside thinking/tool blocks.
      var clone = el.cloneNode(true);
      var stripSelectors = THINKING_SELECTORS.concat(TOOL_SELECTORS, COMMAND_SELECTORS, ARTIFACT_SELECTORS);
      stripSelectors.forEach(function (sel) {
        try { clone.querySelectorAll(sel).forEach(function (n) { n.remove(); }); } catch (e) {}
      });
      var text = (clone.innerText || "").trim();
      if (text) content.push({ type: "text", text: text, format: "markdown", source: "dom" });

      // Code blocks are captured separately to preserve fences/language hints.
      el.querySelectorAll("pre").forEach(function (pre) {
        var codeEl = pre.querySelector("code");
        var lang = "";
        var cls = (codeEl || pre).className || "";
        var m = /language-([\w+-]+)/.exec(cls);
        if (m) lang = m[1];
        var code = (codeEl || pre).innerText;
        if (code && code.trim()) {
          content.push({ type: "text", format: "code", language: lang || null, text: code, source: "dom" });
        }
      });

      if (content.length) {
        messages.push({
          id: "dom_msg_" + i,
          turn_index: i,
          role: role,
          timestamp: null,
          content: content
        });
      }
    });

    return messages;
  }

  function guessToolName(el) {
    var label = el.getAttribute("aria-label") || el.getAttribute("data-testid") || "";
    var firstLine = ((el.innerText || "").split("\n")[0] || "").trim();
    return clip(label || firstLine || "unknown", 60);
  }

  /* ---------- diagnostics (selector recon) ---------- */

  var DEBUG_ROOT_SELECTORS = [
    "main", "[role='main']", "#main", "#root", "#__next", "#app",
    "[id*='chat' i]", "[class*='chat' i]", "[class*='conversation' i]", "[class*='thread' i]"
  ];

  /* The dump exists to tune selectors, and the popup invites the user to share
   * it — so it must carry structure, not content. Text nodes and content-ish
   * attributes are clipped to a recognisable stub; class/data/role attributes
   * (the things selectors actually match on) keep a generous budget. */
  var DEBUG_STRUCTURAL_ATTR_KEEP = 300;
  var DEBUG_HTML_CAP = 40000;
  var STRUCTURAL_ATTR_RE = /^(class|id|role|type|data-(?:testid|state|slot|part)|aria-(?:expanded|hidden|selected|checked|pressed|disabled|level))$/i;
  var DROP_ATTR_RE = /^(srcdoc|src|href|content|value|alt|placeholder)$/i;

  function stub(len) { return "…[+" + len + " chars]"; }

  function redactAttributes(el) {
    var attrs = el.attributes;
    if (!attrs) return;
    for (var i = attrs.length - 1; i >= 0; i--) {
      var name = attrs[i].name;
      var value = attrs[i].value || "";
      if (!value) continue;
      if (DROP_ATTR_RE.test(name) || value.indexOf("data:") === 0) {
        /* srcdoc holds whole generated files; data: URLs hold whole images. */
        try { el.setAttribute(name, "[redacted " + value.length + " chars]"); } catch (e) {}
        continue;
      }
      var structural = STRUCTURAL_ATTR_RE.test(name);
      var cap = DEBUG_STRUCTURAL_ATTR_KEEP;
      if (!structural || value.length > cap) {
        /* Structural values (class lists) are truncated because their prefix is
         * still useful for selectors; content values are replaced outright. */
        var replacement = structural ? value.slice(0, cap) + stub(value.length - cap)
                                     : "[redacted " + value.length + " chars]";
        try { el.setAttribute(name, replacement); } catch (e) {}
      }
    }
  }

  function sanitizedOuterHTML(el) {
    var clone;
    try { clone = el.cloneNode(true); } catch (e) { return ""; }
    try {
      var walker = document.createTreeWalker(clone, NodeFilter.SHOW_TEXT | 128, null);
      var texts = [];
      while (walker.nextNode()) texts.push(walker.currentNode);
      texts.forEach(function (n) {
        var t = n.nodeValue || "";
        /* Anything longer than a UI label is prose. Replace it whole — keeping
         * even a short prefix would still leak the opening of every message. */
        if (t.trim().length) n.nodeValue = "[text " + t.length + " chars]";
      });
      redactAttributes(clone);
      var all = clone.querySelectorAll("*");
      for (var i = 0; i < all.length; i++) redactAttributes(all[i]);
    } catch (e) { return "[DOM redaction unavailable]"; }
    return clone.outerHTML || "";
  }

  /* Same idea for the extractor's own output: keep the shape, drop the prose. */
  var DEBUG_KEEP_KEYS = {
    type: 1, role: 1, format: 1, source: 1, strategy: 1, id: 1, turn_index: 1,
    tool_name: 1, artifact_type: 1, status: 1, language: 1, lane: 1, call_id: 1,
    truncated: 1, timestamp: 1, extracted_at: 1
  };

  AE.dom.redact = function (value, key) {
    if (Array.isArray(value)) return value.map(function (v) { return AE.dom.redact(v); });
    if (value && typeof value === "object") {
      var out = {};
      Object.keys(value).forEach(function (k) { out[k] = AE.dom.redact(value[k], k); });
      return out;
    }
    if (typeof value === "string" && !DEBUG_KEEP_KEYS[key] && value.length) {
      return "[text " + value.length + " chars]";
    }
    return value;
  };

  AE.dom.debugInfo = function () {
    var info = {
      url: location.origin + String(location.pathname || "/").replace(/\/(c|agent)\/[^/]+/, "/$1/[id]"),
      title: "[text " + String(document.title || "").length + " chars]",
      body_class: String(document.body.className || "").slice(0, 300),
      next_data: !!window.document.getElementById("__NEXT_DATA__"),
      redacted: true,
      redaction_note: "All text and content attributes removed; selected structural attributes preserved for selector tuning.",
      selector_hits: {},
      containers: []
    };

    CONTAINER_SELECTORS.concat([FALLBACK_SELECTOR]).forEach(function (sel) {
      try { info.selector_hits[sel] = document.querySelectorAll(sel).length; }
      catch (e) { info.selector_hits[sel] = "error"; }
    });

    // Sample the outer HTML of likely chat roots so real selectors can be
    // derived offline. Bounded hard, and redacted so the dump is shareable.
    var seenRoots = new Set();
    DEBUG_ROOT_SELECTORS.forEach(function (sel) {
      var els;
      try { els = document.querySelectorAll(sel); } catch (e) { return; }
      Array.prototype.forEach.call(els, function (el) {
        if (seenRoots.has(el) || info.containers.length >= 6) return;
        seenRoots.add(el);
        var html = sanitizedOuterHTML(el);
        info.containers.push({
          selector: sel,
          tag: el.tagName,
          id: el.id || null,
          className: String(el.className || "").slice(0, 300),
          html_chars: (el.outerHTML || "").length,
          html_redacted_chars: html.length,
          html: html.slice(0, DEBUG_HTML_CAP)
        });
      });
    });

    return info;
  };

  /* ---------- battle vote + attribution from DOM ----------
   * Arena's ballot has four semantic outcomes: A is better, B is better,
   * Both are good, and Neither. The click is captured by content.js, while
   * this DOM pass handles exports made after a reload and maps revealed model
   * names / green result cards to lanes. */

  function normalizeVoteChoice(value) {
    var t = String(value == null ? "" : value).replace(/\s+/g, " ").trim().toLowerCase();
    if (!t) return null;
    if (/\bneither\b|\bnone\s+(?:are|is)\s+good\b/.test(t)) return "neither_good";
    if (/\bboth\b.*\b(?:good|great|fine|acceptable|better)\b/.test(t) || /\bboth\s+are\s+good\b/.test(t)) return "both_good";
    if (/(?:^|\b)(?:model\s*)?a(?:\b|\s).*(?:\bbetter\b|\bwin(?:s|ner)?\b|\bprefer(?:red)?\b)/.test(t) ||
        /(?:^|\b)(?:choose|select|vote\s+for)\s+(?:model\s*)?a\b/.test(t)) return "A";
    if (/(?:^|\b)(?:model\s*)?b(?:\b|\s).*(?:\bbetter\b|\bwin(?:s|ner)?\b|\bprefer(?:red)?\b)/.test(t) ||
        /(?:^|\b)(?:choose|select|vote\s+for)\s+(?:model\s*)?b\b/.test(t)) return "B";
    if (/^(?:vote|choice|option|model)[ _-]*a(?:[_ -]?(?:better|winner|win))?$/.test(t)) return "A";
    if (/^(?:vote|choice|option|model)[ _-]*b(?:[_ -]?(?:better|winner|win))?$/.test(t)) return "B";
    if (/^a$/.test(t)) return "A";
    if (/^b$/.test(t)) return "B";
    if (/^both(?:[_ -]good)?$/.test(t)) return "both_good";
    if (/^(?:neither|none)(?:[_ -]good)?$/.test(t)) return "neither_good";
    return null;
  }

  AE.dom.normalizeVoteChoice = normalizeVoteChoice;

  AE.dom.isPlaceholderModel = function (name) {
    return AE.isPlaceholderModel ? AE.isPlaceholderModel(name) : /^(?:response|model)\s*[ab]$/i.test(String(name || "").trim());
  };

  /* A ballot control says "A is better" or "Both are good". Anything longer is
   * page prose, and normalizeVoteChoice is loose enough to find "both ... good"
   * or "neither" inside an expanded thinking panel — which is exactly how real
   * exports ended up with fabricated outcomes. Match short labels only. */
  var VOTE_LABEL_MAX = 80;

  /* Shared by the content-script click handler and Node click tests. */
  function inRoleTabSubtree(node) {
    var cur = node;
    while (cur && cur.nodeType === 1) {
      if (cur.getAttribute && cur.getAttribute("role") === "tab") return true;
      cur = cur.parentElement;
    }
    return false;
  }

  AE.dom.voteFromPath = function (path) {
    if (!path || !path.length) return null;
    for (var i = 0; i < path.length; i++) {
      var node = path[i];
      if (!node || node.nodeType !== 1) continue;
      /* Code battles put a disabled "A/B is better" button inside each
       * preview tab. Clicking the surrounding tab produces a trusted event
       * whose composed path contains both labels; it is navigation, never a
       * ballot action. */
      if (inRoleTabSubtree(node)) continue;
      var tag = String(node.tagName || "").toLowerCase();
      var testid = String(node.getAttribute ? node.getAttribute("data-testid") : "" || "");
      var voteAttr = (node.hasAttribute && (node.hasAttribute("data-vote") || node.hasAttribute("data-choice"))) ||
        /vote|better|neither|both/i.test(testid);
      var isControl = tag === "button" || tag === "input" ||
        (node.getAttribute && node.getAttribute("role") === "button") || voteAttr;
      if (!isControl) continue;
      if (node.disabled || (node.getAttribute && node.getAttribute("aria-disabled") === "true")) continue;
      var labelParts = [];
      if (node.getAttribute) {
        ["aria-label", "title", "data-vote", "data-choice", "data-testid"].forEach(function (a) {
          labelParts.push(node.getAttribute(a) || "");
        });
      }
      labelParts.push(node.value || "");
      var attrLabel = labelParts.join(" ").replace(/\s+/g, " ").trim();
      var nodeText = String(node.textContent || "").replace(/\s+/g, " ").trim();
      var label = (attrLabel + " " + nodeText).replace(/\s+/g, " ").trim();
      var choice = label.length <= VOTE_LABEL_MAX ? normalizeVoteChoice(label) : null;
      if (!choice && attrLabel && attrLabel.length <= VOTE_LABEL_MAX) {
        choice = normalizeVoteChoice(attrLabel);
        if (choice) label = attrLabel;
      }
      if (!choice && nodeText && nodeText.length <= VOTE_LABEL_MAX) {
        choice = normalizeVoteChoice(nodeText);
        if (choice) label = nodeText;
      }
      if (!choice) continue;
      var shortAB = /^(?:model\s*)?[ab]$/i.test(String(label || "").replace(/\s+/g, " ").trim());
      if (shortAB && !voteAttr && !inBallotSubtree(node)) continue;
      return { node: node, choice: choice, label: label };
    }
    return null;
  };

  function inBallotSubtree(node) {
    var n = node;
    while (n && n.nodeType === 1) {
      var sig = [
        (n.getAttribute && n.getAttribute("data-testid")) || "",
        (n.getAttribute && n.getAttribute("aria-label")) || "",
        n.className || "",
        n.id || ""
      ].join(" ").toLowerCase();
      if (/vote|ballot|preference|which.?better|neither|both.?good/.test(sig)) return true;
      n = n.parentElement;
    }
    return false;
  }

  function stripTags(html) {
    var t = String(html || "").replace(/<[^>]+>/g, " ");
    t = t.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
         .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ");
    return t.replace(/\s+/g, " ").trim();
  }

  function paneResponseText(pane) {
    var parts = [];
    var prose = pane.querySelectorAll(".prose");
    for (var i = 0; i < prose.length; i++) {
      var t = (prose[i].innerText || "").trim();
      if (t) parts.push(t);
    }
    if (parts.length) return parts.join("\n\n");
    // Fallback: whole pane text minus the "Message from X" header line.
    var all = (pane.innerText || "").replace(/Message from\s+[^\n]+\n?/, "");
    return all.replace(/\s+$/g, "").trim();
  }

  /* Arena's current code-battle UI (2026-09) no longer uses carousel slides
   * or "Message from …" headings. Each lane is a rounded card whose first
   * child is a sticky role=button header ("Option A/B" before the vote, the
   * revealed model afterward). Keep this structural so Tailwind color/class
   * churn does not make the fallback brittle. */
  function modernBattlePanes() {
    var panes = [];
    var seen = [];
    var headers;
    try { headers = document.querySelectorAll('[role="button"]'); } catch (e) { return panes; }
    for (var i = 0; i < headers.length; i++) {
      var header = headers[i];
      var pane = header.parentElement;
      if (!pane || pane.firstElementChild !== header) continue;
      var cls = String(pane.className || "");
      if (cls.indexOf("rounded-xl") === -1 || cls.indexOf("overflow-hidden") === -1) continue;
      var label = compactText(header.innerText || header.textContent || "");
      var whole = compactText(pane.innerText || pane.textContent || "");
      var hasMedia = false;
      try { hasMedia = !!(pane.querySelector("img, video")); } catch (e) { hasMedia = false; }
      if (!label || label.length > 100) continue;
      if (whole.length < label.length + 40 && !hasMedia) continue;
      if (/^(?:created|creating|edited|read|search|explor|deployed|show\s+(?:more|less))\b/i.test(label)) continue;
      if (seen.indexOf(pane) !== -1) continue;
      seen.push(pane);
      panes.push({ pane: pane, header: header, label: label });
    }
    return panes;
  }

  function toolNameFromModernLabel(label) {
    if (/^(?:created|creating|wrote|write)\b/i.test(label)) return "create_file";
    if (/^(?:edited|updated|patched|applied\s+patch)\b/i.test(label)) return "edit_file";
    if (/^(?:ran|running)\b/i.test(label)) return "run_command";
    if (/^read\b/i.test(label)) return "read_file";
    if (/^search\b/i.test(label)) return "grep_files";
    if (/^deployed\b/i.test(label)) return "deploy_project";
    if (/^explor/i.test(label)) return "explore";
    return null;
  }

  function modernPathFromLabel(label) {
    var pathMatch = String(label || "").match(/(?:^|\s)([^\s<>:"|?*]+\.(?:html?|css|js|jsx|ts|tsx|json|md|txt|py|rb|go|rs|java|c|cpp|h|hpp|svg|xml|ya?ml))(?:\s|$)/i);
    return pathMatch ? pathMatch[1] : null;
  }

  function preserveText(el) {
    if (!el) return "";
    var text = typeof el.innerText === "string" ? el.innerText : (el.textContent || "");
    return String(text).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  }

  function cleanBlockText(text) {
    return String(text || "").replace(/^\n+|\n+$/g, "");
  }

  /* Code blocks are rendered as one <span class="line"> per source line.
   * innerText preserves those line breaks and, unlike textContent, keeps the
   * indentation that is part of the tool argument. */
  function codeTextFromDisclosure(target) {
    if (!target) return "";
    var nodes = [];
    try { nodes = toArray(target.querySelectorAll("pre code")); } catch (e) {}
    if (!nodes.length) {
      try { nodes = toArray(target.querySelectorAll("pre")); } catch (e) {}
    }
    return nodes.map(function (node) { return cleanBlockText(preserveText(node)); })
      .filter(function (text) { return !!text; }).join("\n\n");
  }

  function diffLinesFromDisclosure(target) {
    if (!target) return [];
    var nodes = [];
    try { nodes = toArray(target.querySelectorAll("pre code .line, pre .line")); } catch (e) {}
    return nodes.map(function (node) {
      var cls = String(node.className || "").toLowerCase();
      var kind = /\bdiff\s+add\b/.test(cls) ? "add"
        : /\bdiff\s+remove\b/.test(cls) ? "remove" : "context";
      return { kind: kind, text: preserveText(node) };
    });
  }

  /* Return the mounted body of a Radix tool disclosure.  `null` means the
   * panel is still collapsed/unavailable; callers retain the heading summary
   * in that case instead of claiming that an empty body was captured. */
  function modernDisclosureDetail(button) {
    if (!button || typeof document === "undefined") return null;
    var id = button.getAttribute && button.getAttribute("aria-controls");
    if (!id) return null;
    var target = document.getElementById(id);
    if (!target || target.hidden || target.getAttribute("aria-hidden") === "true") return null;
    var code = codeTextFromDisclosure(target);
    var text = cleanBlockText(preserveText(target));
    if (!code && !text) return null;
    var diff = diffLinesFromDisclosure(target);
    return {
      text: text,
      code: code || null,
      diff: diff.length ? diff : null,
      source: "dom_expanded"
    };
  }

  /* Kept public for the small DOM fixture test and for future selector tuning;
   * it exposes no page state beyond the selected disclosure body. */
  AE.dom.captureModernToolDetail = modernDisclosureDetail;

  function pageModality() {
    try {
      var path = String((typeof location !== "undefined" && location.pathname) || "");
      if (/\/image(?:-edit)?(?:\/|$)/i.test(path)) return "image";
      if (/\/video(?:-edit)?(?:\/|$)/i.test(path)) return "video";
      if (/\/code(?:\/|$)/i.test(path)) return "code";
      if (/\/search(?:\/|$)/i.test(path)) return "search";
    } catch (e) { /* ignore */ }
    return null;
  }

  function guessMediaName(url, fallbackExt, index) {
    var ext = fallbackExt || ".png";
    try {
      var u = new URL(String(url), "https://arena.ai/");
      var base = (u.pathname.split("/").pop() || "").split("?")[0];
      if (/\.(png|jpe?g|webp|gif|avif|svg|mp4|webm|mov)$/i.test(base)) return base;
    } catch (e) { /* ignore */ }
    return "image-" + (index + 1) + ext;
  }

  function isUiChromeMedia(el, url) {
    url = String(url || "");
    if (/\/_next\/static\//i.test(url)) return true;
    if (/favicon|sprite|emoji-icon/i.test(url)) return true;
    var w = 0, h = 0;
    try {
      w = el.naturalWidth || el.videoWidth || parseInt(el.getAttribute("width") || "0", 10) || 0;
      h = el.naturalHeight || el.videoHeight || parseInt(el.getAttribute("height") || "0", 10) || 0;
    } catch (e) { /* ignore */ }
    if ((w && w < 48) || (h && h < 48)) return true;
    return false;
  }

  function collectMediaFromPane(pane) {
    var files = [];
    var seen = {};
    if (!pane) return files;
    function add(url, kind, el) {
      if (!url || seen[url]) return;
      if (!/^(https?:|blob:|data:image|data:video)/i.test(url)) return;
      if (el && isUiChromeMedia(el, url)) return;
      seen[url] = true;
      var video = kind === "video" || /\.(mp4|webm|mov)(\?|$)/i.test(url);
      var ext = video ? ".mp4" : ".png";
      var rec = {
        path: guessMediaName(url, ext, files.length),
        contentType: video ? "video/mp4" : "image/png",
        source: "dom"
      };
      if (url.indexOf("data:") === 0) rec.content = url;
      else rec.downloadUrl = url;
      files.push(rec);
    }
    try {
      toArray(pane.querySelectorAll("img")).forEach(function (img) {
        add(img.currentSrc || img.src, "image", img);
      });
      toArray(pane.querySelectorAll("video")).forEach(function (vid) {
        add(vid.currentSrc || vid.src, "video", vid);
        toArray(vid.querySelectorAll("source")).forEach(function (src) {
          add(src.src, "video", vid);
        });
      });
    } catch (e) { /* ignore */ }
    return files;
  }

  function mergeFiles(into, extra) {
    var out = Array.isArray(into) ? into.slice() : [];
    var seen = {};
    out.forEach(function (f) {
      var k = (f && (f.downloadUrl || f.url || f.path)) || "";
      if (k) seen[k] = true;
    });
    (extra || []).forEach(function (f) {
      if (!f) return;
      var k = f.downloadUrl || f.url || f.path;
      if (k && seen[k]) return;
      if (k) seen[k] = true;
      out.push(f);
    });
    return out;
  }

  AE.dom.collectMediaFromPane = collectMediaFromPane;
  AE.dom.pageModality = pageModality;

  function modernPaneData(item) {
    var pane = item.pane;
    var response = paneResponseText(pane);
    var tools = [];
    var toolCalls = [];
    var files = [];
    var fileSeen = {};
    var controls = pane.querySelectorAll('button, [role="button"]');
    for (var i = 0; i < controls.length; i++) {
      if (controls[i] === item.header) continue;
      var label = compactText(controls[i].innerText || controls[i].textContent || "");
      if (!label || label.length > 240) continue;
      var toolName = toolNameFromModernLabel(label);
      if (!toolName) continue;
      if (tools.indexOf(toolName) === -1) tools.push(toolName);
      var path = modernPathFromLabel(label);
      var detail = modernDisclosureDetail(controls[i]);
      var isEdit = toolName === "edit_file";
      var args = path ? { path: path } : null;
      var call = {
        toolCallId: null,
        toolName: toolName,
        args: args,
        summary: label,
        source: "dom"
      };
      if (detail) {
        call.detail_source = detail.source;
        if (detail.code) {
          if (!args) args = {};
          /* Created/Wrote rows contain the file argument. Edited rows render
           * a patch, so label it as such rather than pretending it is the
           * complete post-edit file. */
          if (isEdit) args.patch = detail.code;
          else args.content = detail.code;
          call.args = args;
          if (isEdit && detail.diff) call.diff = detail.diff;
          if (!isEdit && toolName !== "create_file") call.output = detail.code;
        } else if (detail.text) {
          call.output = detail.text;
        }
      }
      toolCalls.push(call);
      if (path && (toolName === "create_file" || toolName === "edit_file") && !fileSeen[path]) {
        fileSeen[path] = true;
        var file = {
          path: path,
          contentType: null,
          content: detail && !isEdit && detail.code ? detail.code : null,
          tool: toolName,
          source: "dom"
        };
        if (detail && isEdit && detail.code) {
          file.patch = detail.code;
          if (detail.diff) file.diff = detail.diff;
        }
        files.push(file);
      } else if (path && (toolName === "create_file" || toolName === "edit_file") && detail && detail.code) {
        /* Keep the first archive path per file, but retain later edit patches
         * in the JSON so no tool body disappears when a file is edited again. */
        var existingFile = files.filter(function (f) { return f && f.path === path; })[0];
        if (existingFile && isEdit) {
          if (!existingFile.patches) existingFile.patches = [];
          existingFile.patches.push(detail.code);
          if (detail.diff) {
            if (!existingFile.diffs) existingFile.diffs = [];
            existingFile.diffs.push(detail.diff);
          }
        } else if (existingFile && !isEdit && !existingFile.content) {
          existingFile.content = detail.code;
          existingFile.tool = toolName;
        }
      }
    }
    var completeText = compactText(pane.innerText || pane.textContent || "");
    return {
      label: item.label,
      response: response,
      finished: /\bdeployed the project\b|\bimplementation is complete\b|\bcomplete and verified\b/i.test(completeText),
      tools: tools,
      tool_calls: toolCalls,
      files: mergeFiles(files, collectMediaFromPane(pane)),
      code: files.length > 0
    };
  }

  function sliceResponsesBetweenHeaders(models) {
    var html = document.body.innerHTML || "";
    var re = /Message from\s+([^<"]{1,60})/g;
    var m, matches = [];
    while ((m = re.exec(html))) matches.push({ end: re.lastIndex, next: m.index });
    var last = matches.slice(-2);
    var out = [null, null];
    for (var i = 0; i < last.length; i++) {
      var start = last[i].end;
      var end = (i + 1 < last.length) ? last[i + 1].next : html.length;
      if (end - start > 20000) end = start + 20000;
      out[i] = stripTags(html.slice(start, end));
    }
    return out;
  }

  function compactText(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function controlLabel(el) {
    if (!el) return "";
    return compactText([
      el.getAttribute("aria-label") || "",
      el.getAttribute("title") || "",
      el.getAttribute("data-vote") || "",
      el.getAttribute("data-choice") || "",
      el.getAttribute("data-testid") || "",
      el.getAttribute("name") || "",
      el.getAttribute("value") || "",
      el.textContent || ""
    ].join(" "));
  }

  function isVoteControl(el) {
    if (!el || el.nodeType !== 1) return false;
    var tag = String(el.tagName || "").toLowerCase();
    if (el.getAttribute("role") === "tab") return false;
    return tag === "button" || tag === "input" || el.getAttribute("role") === "button" ||
      el.hasAttribute("data-vote") || el.hasAttribute("data-choice") ||
      /vote|better|neither|both/i.test(String(el.getAttribute("data-testid") || ""));
  }

  function isVisible(el) {
    if (!el) return false;
    if (el.hidden || el.getAttribute("aria-hidden") === "true") return false;
    var cls = String(el.className || "").toLowerCase();
    if (/(^|[\s_:\-])hidden(?:$|[\s_:\-])/.test(cls)) return false;
    try {
      var style = window.getComputedStyle(el);
      if (style.display === "none" || style.visibility === "hidden") return false;
    } catch (e) { /* computed style unavailable in a diagnostic context */ }
    return true;
  }

  function hasTruthyState(el) {
    var attrs = ["aria-pressed", "aria-selected", "aria-checked", "data-selected", "data-checked", "data-active", "data-state", "data-voted"];
    for (var i = 0; i < attrs.length; i++) {
      var value = el.getAttribute(attrs[i]);
      if (value && /^(true|yes|on|selected|checked|active|pressed|chosen|voted)$/i.test(value)) return true;
    }
    try {
      if (el.matches(":checked, :selected")) return true;
    } catch (e) { /* selector may not apply to this element */ }
    var cls = String(el.className || "").toLowerCase();
    if (/(^|[\s_-])(?:selected|checked|pressed|chosen|current|voted)(?:$|[\s_-])/.test(cls)) return true;
    return false;
  }

  function collectVoteControls() {
    var out = [];
    var selector = 'button, [role="button"], input[type="button"], input[type="submit"], [data-vote], [data-choice], [data-testid*="vote" i], [aria-label*="better" i]';
    var els;
    try { els = document.querySelectorAll(selector); } catch (e) { return out; }
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      if (!isVoteControl(el)) continue;
      var label = controlLabel(el);
      var choice = normalizeVoteChoice(label);
      if (!choice) continue;
      out.push({
        el: el,
        choice: choice,
        label: label,
        selected: hasTruthyState(el),
        visible: isVisible(el),
        disabled: !!el.disabled || el.getAttribute("aria-disabled") === "true"
      });
    }
    return out;
  }

  function selectedVoteFromControls(controls) {
    var selected = controls.filter(function (c) { return c.selected; });
    var choices = [];
    selected.forEach(function (c) {
      if (choices.indexOf(c.choice) === -1) choices.push(c.choice);
    });
    if (!choices.length) return null;
    // A UI that highlights both individual lanes is equivalent to "Both are good".
    if (choices.indexOf("both_good") !== -1) return { choice: "both_good", label: selected[0].label, source: "dom_selection" };
    if (choices.indexOf("neither_good") !== -1) return { choice: "neither_good", label: selected[0].label, source: "dom_selection" };
    if (choices.indexOf("A") !== -1 && choices.indexOf("B") !== -1) return { choice: "both_good", label: "A and B selected", source: "dom_selection" };
    if (choices.length === 1) return { choice: choices[0], label: selected[0].label, source: "dom_selection" };
    return null;
  }

  function headerCandidates() {
    var candidates = [];
    var els;
    try { els = document.querySelectorAll("body *"); } catch (e) { return candidates; }
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var text = compactText(el.textContent || "");
      if (text.length < 13 || text.length > 100) continue;
      var m = text.match(/^Message\s+from\s+(.{1,80})$/i);
      if (!m) continue;
      candidates.push({ name: compactText(m[1]), node: el });
    }
    // Keep the innermost exact-text element when wrappers repeat the header.
    return candidates.filter(function (candidate, index, all) {
      return !all.some(function (other, j) {
        return j !== index && other.node !== candidate.node &&
          other.node.contains(candidate.node) &&
          compactText(other.node.textContent || "") === compactText(candidate.node.textContent || "");
      });
    });
  }

  function sortHeaders(headers) {
    return headers.slice().sort(function (a, b) {
      if (a.node === b.node) return 0;
      var rel = a.node.compareDocumentPosition(b.node);
      if (rel & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
      if (rel & Node.DOCUMENT_POSITION_PRECEDING) return 1;
      return 0;
    });
  }

  function headerForGreenElement(green, headers) {
    if (!green) return null;
    // Most Arena result borders are on the pane/card that contains its header.
    for (var i = 0; i < headers.length; i++) {
      if (green === headers[i].node || green.contains(headers[i].node)) return headers[i];
    }
    // If the positive class is on a descendant of the pane, climb until the
    // ancestor contains exactly one revealed model header.
    var cur = green.parentElement;
    while (cur && cur !== document.body) {
      var local = headers.filter(function (h) { return cur.contains(h.node); });
      if (local.length === 1) return local[0];
      cur = cur.parentElement;
    }
    // Last-resort document-order attribution for split/custom DOM nodes.
    var best = null;
    for (var j = 0; j < headers.length; j++) {
      var relation = headers[j].node.compareDocumentPosition(green);
      if (relation & Node.DOCUMENT_POSITION_FOLLOWING) best = headers[j];
    }
    return best;
  }

  AE.dom.battleInfo = function () {
    var models = [];
    var vote = null;
    var winnerModel = null;
    var greenLanes = [];
    var negativeLanes = [];
    var controls = [];
    var ballotVisible = false;
    var responses = [null, null];
    var laneData = [null, null];
    try {
      controls = collectVoteControls();
      ballotVisible = controls.some(function (c) { return c.visible && !c.disabled; });
      vote = selectedVoteFromControls(controls);

      var headers = sortHeaders(headerCandidates());
      // A /c/ page can hold several battles. Attribute the current result to the
      // latest pair, matching the latest evaluation stream captured by the SW.
      var lastTwo = headers.slice(-2);
      models = lastTwo.map(function (h) { return h.name; }).filter(function (n) {
        return n && !(AE.isPlaceholderModel && AE.isPlaceholderModel(n));
      });

      var modern = modernBattlePanes();
      var lastModern = modern.length >= 2 ? modern.slice(-2) : [];
      if (lastModern.length === 2) {
        laneData = [modernPaneData(lastModern[0]), modernPaneData(lastModern[1])];
        responses = [laneData[0].response, laneData[1].response];
        var modernModels = laneData.map(function (lane) { return lane.label; }).filter(function (n) {
          return n && !(AE.isPlaceholderModel && AE.isPlaceholderModel(n)) &&
            !/^(?:option|response|model)\s*[ab]$/i.test(n);
        });
        if (modernModels.length === 2) models = modernModels;
        greenLanes = [];
        negativeLanes = [];
        lastModern.forEach(function (item, idx) {
          var cls = String(item.pane.className || "").toLowerCase();
          var lane = idx === 0 ? "A" : "B";
          if (/border-interactive-positive|bg-interactive-positive/.test(cls)) greenLanes.push(lane);
          if (/border-interactive-negative|border-negative|border-red/.test(cls)) negativeLanes.push(lane);
        });
        if (greenLanes.length === 1 && models.length === 2) {
          winnerModel = models[greenLanes[0] === "A" ? 0 : 1];
        }
      }

      var greenSelector = '[class*="border-interactive-positive" i], [class*="bg-interactive-positive" i], [data-winner="true"], [aria-label*="winner" i]';
      var greenEls = document.querySelectorAll(greenSelector);
      for (var gi = 0; gi < greenEls.length; gi++) {
        var header = headerForGreenElement(greenEls[gi], lastTwo);
        if (!header) continue;
        var lane = lastTwo.indexOf(header) === 0 ? "A" : lastTwo.indexOf(header) === 1 ? "B" : null;
        if (lane && greenLanes.indexOf(lane) === -1) greenLanes.push(lane);
      }
      var negativeSelector = '[class*="border-interactive-negative" i], [class*="border-negative" i], [class*="border-red" i]';
      var negativeEls = document.querySelectorAll(negativeSelector);
      for (var ni = 0; ni < negativeEls.length; ni++) {
        var negativeHeader = headerForGreenElement(negativeEls[ni], lastTwo);
        if (!negativeHeader) continue;
        var negativeLane = lastTwo.indexOf(negativeHeader) === 0 ? "A" : lastTwo.indexOf(negativeHeader) === 1 ? "B" : null;
        if (negativeLane && negativeLanes.indexOf(negativeLane) === -1) negativeLanes.push(negativeLane);
      }
      if (!vote && greenLanes.length === 1 && models.length === 2) {
        winnerModel = models[greenLanes[0] === "A" ? 0 : 1];
      }

      // ---- Pane-aware pass (more accurate winner + response text) ----
      // Each battle pane is a carousel slide containing its own "Message from"
      // header, result card, and response prose. When present, use slide
      // containment for the winner (exact) and extract the visible response.
      var slides = document.querySelectorAll('[aria-roledescription="slide"]');
      if (slides.length >= 2) {
        var slidePanes = [];
        for (var si = 0; si < slides.length; si++) {
          var sm = (slides[si].innerHTML || "").match(/Message from\s+([^<"]{1,60})/);
          slidePanes.push({
            model: sm ? sm[1].trim() : null,
            green: !!slides[si].querySelector('[class*="border-interactive-positive" i]'),
            response: paneResponseText(slides[si])
          });
        }
        var lastSlides = slidePanes.slice(-2);
        if (lastSlides.length === 2 && lastSlides[0].model && lastSlides[1].model) {
          var slideModels = [lastSlides[0].model, lastSlides[1].model].filter(function (n) {
            return n && !(AE.isPlaceholderModel && AE.isPlaceholderModel(n));
          });
          if (slideModels.length === 2) models = slideModels;
          responses = [lastSlides[0].response, lastSlides[1].response];
          var greenIdx = -1;
          for (var g2 = 0; g2 < 2; g2++) if (lastSlides[g2].green) greenIdx = g2;
          var greenCount = lastSlides.filter(function (p) { return p.green; }).length;
          if (greenCount === 1) { winnerModel = models[greenIdx]; greenLanes = [greenIdx === 0 ? "A" : "B"]; }
        }
      } else if (lastModern.length !== 2) {
        // Fallback: response text = rendered HTML between consecutive headers.
        responses = sliceResponsesBetweenHeaders(models);
      }

      // A selected ballot control is stronger than the presence of its label.
      // `preVoteBallot` is therefore false after a selected/disabled result,
      // unlike the old body-wide text regex which stayed true on /c/ pages.
      if (!vote) {
        var disabledChoices = controls.filter(function (c) { return c.disabled; }).map(function (c) { return c.choice; });
        var uniqueDisabled = disabledChoices.filter(function (x, i, a) { return a.indexOf(x) === i; });
        if (uniqueDisabled.length === 1 && !ballotVisible) {
          vote = { choice: uniqueDisabled[0], label: "disabled ballot control", source: "dom_disabled_control" };
        }
      }
    } catch (e) { /* ignore */ }
    var modality = pageModality();
    if (!modality) {
      var hasImg = laneData.some(function (ln) {
        return ln && Array.isArray(ln.files) && ln.files.some(function (f) {
          return f && /^image\//i.test(f.contentType || "") || (f && /\.(png|jpe?g|webp|gif|avif)(\?|$)/i.test(f.path || f.downloadUrl || ""));
        });
      });
      if (hasImg) modality = "image";
    }
    return {
      models: models,
      anonymous: models.length < 2,
      preVoteBallot: ballotVisible && !vote,
      ballotVisible: ballotVisible,
      vote: vote,
      vote_choice: vote ? vote.choice : null,
      greenLanes: greenLanes,
      negativeLanes: negativeLanes,
      winnerModel: winnerModel,
      responses: responses,
      lanes: laneData,
      modality: modality
    };
  };

  /* ---------- attachment fetching (ported from v1.4.0 fork) ----------
   * Fetch artifact bytes same-origin (credentials included so preview-token
   * URLs work while logged in) and return them as data URLs. Bounded.
   * Only arena.ai (and blob:) URLs are fetched — a redirected content_or_url
   * must not become a credentialed request to a third party. */
  var ATTACHMENT_MAX_BYTES = 15 * 1024 * 1024;

  AE.dom.isAllowedAttachmentUrl = function (url) {
    try {
      var base = "https://arena.ai/";
      try {
        if (typeof location !== "undefined" && location.href) base = location.href;
      } catch (e) { /* tests */ }
      var u = new URL(String(url), base);
      if (u.protocol === "blob:") return true;
      if (u.protocol !== "https:") return false;
      if (/^([a-z0-9-]+\.)*(arena\.ai|lmarena\.ai)$/i.test(u.hostname)) return true;
      if (/(^|\.)r2\.dev$/i.test(u.hostname)) return true;
      if (/(^|\.)r2\.cloudflarestorage\.com$/i.test(u.hostname)) return true;
      return false;
    } catch (e) {
      return false;
    }
  };

  AE.dom.fetchAttachment = function (url) {
    if (!AE.dom.isAllowedAttachmentUrl(url)) {
      return Promise.resolve({ url: url, ok: false, error: "blocked origin" });
    }
    var arenaHost = false;
    try { arenaHost = /^([a-z0-9-]+\.)*(arena\.ai|lmarena\.ai)$/i.test(new URL(String(url), "https://arena.ai/").hostname); } catch (e) { arenaHost = false; }
    return fetch(url, { credentials: arenaHost ? "include" : "omit", cache: "no-store" })
      .then(function (resp) {
        if (!resp.ok) return { url: url, ok: false, error: "HTTP " + resp.status };
        var ct = "";
        try { ct = (resp.headers.get("content-type") || "").split(";")[0]; } catch (e) { /* ignore */ }
        return resp.blob().then(function (blob) {
          if (blob.size > ATTACHMENT_MAX_BYTES) {
            return { url: url, ok: false, error: "too large (" + Math.round(blob.size / 1024) + " KB)" };
          }
          return new Promise(function (resolve) {
            var fr = new FileReader();
            fr.onload = function () { resolve({ url: url, ok: true, dataUrl: fr.result, bytes: blob.size, contentType: ct }); };
            fr.onerror = function () { resolve({ url: url, ok: false, error: "read error" }); };
            try { fr.readAsDataURL(blob); } catch (e) { resolve({ url: url, ok: false, error: "read error" }); }
          });
        });
      })
      .catch(function (e) {
        return { url: url, ok: false, error: String((e && e.message) || e).slice(0, 120) };
      });
  };
})();

;
// Source: src/history-backfill.js
/* One-click backfill of the signed-in user's Arena history.
 *
 * Runs in the isolated content script (same-origin cookies) to list and
 * fetch conversations, then the background converts each record to schema
 * 2.0 and writes it through the native/downloads archive sink.
 *
 * Endpoints (session-authenticated, unofficial):
 *   GET /api/history/unified?limit=&includeArchived=&cursor=
 *   GET /api/history/list?...          (fallback)
 *   GET /api/evaluation/{uuid}
 *   GET /agent/{uuid}                  (HTML / Next flight for agentic)
 */
var AE = AE || {};

(function () {
  "use strict";

  var UUID_RE = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i;
  var PAGE_SIZE = 20;
  var PAGE_GUARD = 200;
  var ITEM_GAP_MS = 180;

  AE.historyUuid = function (text) {
    var m = UUID_RE.exec(String(text || ""));
    return m ? m[1].toLowerCase() : null;
  };

  function wait(ms) {
    return new Promise(function (resolve) { setTimeout(resolve, ms); });
  }

  function asText(v) {
    if (v == null) return "";
    if (typeof v === "string") return v;
    if (Array.isArray(v)) {
      return v.map(function (p) {
        if (typeof p === "string") return p;
        if (p && typeof p === "object") {
          if (typeof p.text === "string") return p.text;
          if (p.type === "image_url") return "[image] " + ((p.image_url && p.image_url.url) || "");
        }
        try { return JSON.stringify(p); } catch (e) { return String(p); }
      }).join("\n");
    }
    if (typeof v === "object") {
      if (typeof v.text === "string") return v.text;
      if (Array.isArray(v.parts)) return asText(v.parts);
      try { return JSON.stringify(v); } catch (e) { return String(v); }
    }
    return String(v);
  }

  AE.historyNormalizeContent = asText;

  async function fetchJson(url) {
    var res = await fetch(url, {
      method: "GET",
      credentials: "include",
      headers: { Accept: "application/json, text/plain, */*" }
    });
    if (!res.ok) {
      var body = "";
      try { body = (await res.text()).slice(0, 240); } catch (e) { /* ignore */ }
      var err = new Error("HTTP " + res.status + (body ? " " + body : ""));
      err.status = res.status;
      throw err;
    }
    var json = await res.json();
    return unwrapApi(json);
  }

  function unwrapApi(json) {
    if (!json || typeof json !== "object") return json;
    var inner = json.payload;
    if (inner && typeof inner === "object" && !Array.isArray(inner)) {
      if (inner.entries || inner.history || inner.items || inner.messages || inner.pagination || inner.id) {
        return inner;
      }
    }
    if (json.data && typeof json.data === "object" && !Array.isArray(json.data)) {
      var d = json.data;
      if (d.entries || d.history || d.items || d.messages || d.pagination || d.id) return d;
    }
    return json;
  }

  async function fetchText(url) {
    var res = await fetch(url, {
      method: "GET",
      credentials: "include",
      headers: { Accept: "text/html,application/xhtml+xml,application/json" }
    });
    if (!res.ok) {
      var err = new Error("HTTP " + res.status);
      err.status = res.status;
      throw err;
    }
    return res.text();
  }

  function historyBatch(payload) {
    if (!payload) return [];
    if (Array.isArray(payload.entries)) return payload.entries;
    if (Array.isArray(payload.history)) return payload.history;
    if (Array.isArray(payload.items)) return payload.items;
    if (Array.isArray(payload)) return payload;
    return [];
  }

  AE.historyListAll = async function (hooks) {
    hooks = hooks || {};
    var merged = [];
    var cursor = null;
    var page = 0;
    var endpoints = ["/api/history/unified", "/api/history/list"];
    var endpoint = endpoints[0];
    while (page < PAGE_GUARD) {
      var params = new URLSearchParams();
      params.set("limit", String(PAGE_SIZE));
      params.set("includeArchived", "true");
      if (cursor) params.set("cursor", cursor);
      var url = location.origin + endpoint + "?" + params.toString();
      var payload;
      try {
        payload = await fetchJson(url);
      } catch (e) {
        if (page === 0 && endpoint === endpoints[0] && e && e.status === 404) {
          endpoint = endpoints[1];
          continue;
        }
        throw e;
      }
      var batch = historyBatch(payload);
      merged.push.apply(merged, batch);
      page += 1;
      if (hooks.onPage) hooks.onPage({ page: page, count: merged.length });
      var pag = payload && payload.pagination ? payload.pagination : {};
      var hasMore = pag.hasMore === true || pag.has_more === true;
      var next = typeof pag.cursor === "string" ? pag.cursor : (typeof pag.nextCursor === "string" ? pag.nextCursor : null);
      if (!hasMore || !next || !batch.length) break;
      cursor = next;
    }
    var seen = {};
    var out = [];
    merged.forEach(function (item) {
      var id = AE.historyUuid(item && (item.id || item.evaluationId || item.sessionId || item.conversationId));
      if (!id || seen[id]) return;
      seen[id] = true;
      var type = String((item && item.type) || "evaluation");
      if (type !== "agentic") type = "evaluation";
      out.push({
        id: id,
        type: type,
        title: String((item && (item.title || item.name)) || ""),
        mode: String((item && item.mode) || ""),
        createdAt: (item && (item.createdAt || item.created_at)) || "",
        updatedAt: (item && (item.updatedAt || item.updated_at)) || ""
      });
    });
    return out;
  };

  function extractJsonObjectAt(text, start) {
    var depth = 0, inStr = false, esc = false;
    for (var i = start; i < text.length; i++) {
      var c = text.charAt(i);
      if (inStr) {
        if (esc) esc = false;
        else if (c === "\\") esc = true;
        else if (c === "\"") inStr = false;
        continue;
      }
      if (c === "\"") { inStr = true; continue; }
      if (c === "{") depth++;
      else if (c === "}") {
        depth--;
        if (depth === 0) return text.slice(start, i + 1);
      }
    }
    return null;
  }

  function parseAgentHtml(html, id, meta) {
    if (AE.parsePageData) {
      var page = AE.parsePageData(html, location.origin + "/agent/" + id);
      if (page.transcript) return Object.assign({}, page.transcript, {
        id: id, type: "agentic", title: (meta && meta.title) || "", createdAt: (meta && meta.createdAt) || "",
        pageUrl: location.origin + "/agent/" + id
      });
    }
    var flight = "";
    var re = /self\.__next_f\.push\(\[1,"((?:\\.|[^"\\])*)"\]\)<\/script>/g;
    var m;
    while ((m = re.exec(html))) {
      try { flight += JSON.parse("\"" + m[1] + "\""); } catch (e) { /* skip chunk */ }
    }
    var search = flight || html;
    var idx = 0;
    while (idx < search.length) {
      var start = search.indexOf("{\"messages\":[", idx);
      if (start < 0) break;
      var objText = extractJsonObjectAt(search, start);
      if (!objText) break;
      try {
        var cand = JSON.parse(objText);
        if (Array.isArray(cand.messages) && cand.messages.some(function (msg) {
          return msg && (Array.isArray(msg.parts) || msg.role);
        })) {
          cand.id = id;
          cand.type = "agentic";
          cand.title = (meta && meta.title) || cand.title || "";
          cand.createdAt = (meta && meta.createdAt) || cand.createdAt || "";
          cand.pageUrl = location.origin + "/agent/" + id;
          return cand;
        }
      } catch (e) { /* keep scanning */ }
      idx = start + 1;
    }
    return null;
  }

  AE.historyFetchRecord = async function (item) {
    var id = AE.historyUuid(item && (item.id || item));
    if (!id) throw new Error("invalid id");
    var type = String((item && item.type) || "evaluation");
    if (type === "agentic") {
      var html = await fetchText(location.origin + "/agent/" + id);
      var agent = parseAgentHtml(html, id, item);
      if (!agent) throw new Error("agent payload missing");
      return agent;
    }
    try {
      return await fetchJson(location.origin + "/api/evaluation/" + id);
    } catch (e) {
      if (e && e.status === 404) {
        var html2 = await fetchText(location.origin + "/agent/" + id);
        var agent2 = parseAgentHtml(html2, id, item);
        if (agent2) return agent2;
      }
      throw e;
    }
  };

  AE.historyPullAll = async function (hooks) {
    hooks = hooks || {};
    var list = await AE.historyListAll(hooks);
    if (hooks.onList) hooks.onList({ total: list.length });
    var records = [];
    var failed = [];
    for (var i = 0; i < list.length; i++) {
      if (hooks.onItem) hooks.onItem({ index: i + 1, total: list.length, item: list[i] });
      try {
        var rec = await AE.historyFetchRecord(list[i]);
        rec._historyMeta = list[i];
        records.push(rec);
      } catch (e) {
        failed.push({ id: list[i].id, type: list[i].type, error: String(e && e.message ? e.message : e) });
      }
      await wait(ITEM_GAP_MS);
    }
    return { list: list, records: records, failed: failed };
  };

  function modelOf(message, evaluation, lane) {
    var m = message || {};
    var name = m.modelName || m.model || m.model_name || m.publicName;
    if (name && typeof name === "object") name = AE.catalogModelLabel(name);
    if (typeof name === "string" && name && !AE.isPlaceholderModel(name)) return name;
    var ev = evaluation || {};
    if (lane === "A") name = ev.modelA || ev.model_a || (ev.models && ev.models[0]);
    if (lane === "B") name = ev.modelB || ev.model_b || (ev.models && ev.models[1]);
    if (name && typeof name === "object") name = AE.catalogModelLabel(name);
    if (typeof name === "string" && name && !AE.isPlaceholderModel(name)) return name;
    return null;
  }

  function mediaBasename(path, url, index, contentType) {
    var name = String(path || "").replace(/\\/g, "/").split("/").pop();
    if (url) {
      try {
        var u = new URL(url, "https://arena.ai/");
        var fromUrl = (u.pathname.split("/").pop() || "").split("?")[0];
        if (fromUrl && /\.(png|jpe?g|webp|gif|avif|svg|mp4|webm|mov)$/i.test(fromUrl)) name = fromUrl;
        else if (!name) name = fromUrl;
      } catch (e) { /* keep */ }
    }
    if (name) name = name.split("?")[0];
    var ext = "";
    var ct = String(contentType || "").toLowerCase();
    if (/jpeg|jpg/.test(ct)) ext = ".jpeg";
    else if (/png/.test(ct)) ext = ".png";
    else if (/webp/.test(ct)) ext = ".webp";
    else if (/gif/.test(ct)) ext = ".gif";
    else if (/mp4/.test(ct)) ext = ".mp4";
    if (!name || !/\./.test(name)) name = "image-" + (index + 1) + (ext || ".png");
    else if (ext && !/\.(png|jpe?g|webp|gif|avif|svg|mp4|webm|mov)$/i.test(name)) name += ext;
    return name;
  }

  function filesFromMessage(message) {
    var out = [];
    var seen = {};
    function add(obj) {
      if (obj == null) return;
      if (typeof obj === "string") {
        if (/^https?:/i.test(obj) || obj.indexOf("data:image") === 0) add({ url: obj });
        return;
      }
      if (typeof obj !== "object") return;
      var nested = obj.image_url && typeof obj.image_url === "object" ? obj.image_url : null;
      var url = obj.url || obj.downloadUrl || obj.href || obj.src || (nested && (nested.url || nested.href)) || null;
      var path = obj.name || obj.filename || obj.path || (nested && nested.path) || null;
      var ct = obj.contentType || obj.mimeType || obj.media_type || (nested && nested.contentType) || null;
      var content = typeof obj.content === "string" ? obj.content : null;
      if (!url && !content) return;
      if (url && seen[url]) return;
      if (url) seen[url] = true;
      out.push({
        path: mediaBasename(path, url, out.length, ct),
        downloadUrl: url && String(url).indexOf("data:") === 0 ? null : url,
        content: content || (url && String(url).indexOf("data:") === 0 ? url : null),
        contentType: ct || null
      });
    }
    var buckets = [message && message.experimental_attachments, message && message.attachments, message && message.files];
    buckets.forEach(function (arr) {
      if (Array.isArray(arr)) arr.forEach(add);
    });
    var content = message && message.content;
    if (Array.isArray(content)) {
      content.forEach(function (part) {
        if (!part || typeof part !== "object") return;
        var typ = String(part.type || "");
        if (typ === "image_url" || typ === "image" || typ === "file" || typ === "media") add(part.image_url || part);
      });
    }
    return out;
  }

  function attachmentsToFiles(message) {
    return filesFromMessage(message);
  }

  function voteFromEvaluation(ev) {
    var v = ev && (ev.vote || ev.vote_choice || ev.preference || ev.winner || ev.outcome);
    if (!v) return { choice: null, outcome: null };
    var t = String(v).toLowerCase();
    if (t === "a" || t === "model_a" || t === "left") return { choice: "A", outcome: "a_wins" };
    if (t === "b" || t === "model_b" || t === "right") return { choice: "B", outcome: "b_wins" };
    if (t.indexOf("both") !== -1) return { choice: "both_good", outcome: "both_good" };
    if (t.indexOf("neither") !== -1) return { choice: "neither_good", outcome: "neither_good" };
    return { choice: null, outcome: t };
  }

  function subtypeOf(ev, contestants) {
    var raw = String((ev && (ev.subtype || ev.category || ev.task || ev.game || ev.mode || ev.modality)) || "").toLowerCase();
    if (/code|webdev|web-dev/.test(raw)) return "code";
    if (/image/.test(raw)) return "image";
    if (/video/.test(raw)) return "video";
    if (/search/.test(raw)) return "web-search";
    var files = [];
    (contestants || []).forEach(function (c) { (c.files || []).forEach(function (f) { files.push(f); }); });
    if (files.some(function (f) { return /^video\//i.test(f.contentType || "") || /\.(mp4|webm|mov)$/i.test(f.path || ""); })) return "video";
    if (files.some(function (f) { return /^image\//i.test(f.contentType || "") || /\.(png|jpe?g|webp|gif|avif|svg)$/i.test(f.path || ""); })) return "image";
    return "text";
  }

  AE.historyEvaluationToPayload = function (ev, meta) {
    ev = ev || {};
    var selectedMode = /^(direct|direct-battle|side-by-side)$/.test(ev.mode || "");
    var id = AE.historyUuid(ev.id || ev.evaluationId || (meta && meta.id));
    var vote = voteFromEvaluation(ev);
    var msgs = Array.isArray(ev.messages) ? ev.messages : [];
    var battles = [];
    var thread = [];
    var i = 0;
    while (i < msgs.length) {
      var m = msgs[i] || {};
      var role = String(m.role || "").toLowerCase();
      if (role === "user") {
        var prompt = asText(m.content);
        var assistants = [];
        i++;
        while (i < msgs.length && String((msgs[i] || {}).role || "").toLowerCase() === "assistant") {
          assistants.push(msgs[i]);
          i++;
        }
        if (assistants.length >= 2) {
          var contestants = assistants.map(function (a, idx) {
            var lane = String(a.participantPosition || a.position || "").toUpperCase();
            if (lane !== "A" && lane !== "B") lane = idx === 0 ? "A" : "B";
            return {
              lane: lane,
              model: modelOf(a, ev, lane),
              model_source: modelOf(a, ev, lane) ? "history_metadata" : "unknown",
              model_identity_verified: false,
              model_id: a.modelId || a.model_id || (lane === "A" ? ev.modelAId : ev.modelBId) || null,
              message_id: a.id || null,
              response: asText(a.content),
              finished: true,
              files: attachmentsToFiles(a),
              tools: [],
              tool_calls: []
            };
          });
          battles.push({
            evaluation_id: id,
            mode: ev.mode || "battle",
            subtype: subtypeOf(ev, contestants),
            prompt: prompt,
            anonymous: !contestants.some(function (c) { return c.model; }),
            contestants: contestants,
            vote_choice: selectedMode ? null : vote.choice,
            outcome: selectedMode ? "not_applicable" : vote.outcome || "pending",
            workspace_files: []
          });
        } else {
          thread.push({
            id: m.id || ("user-" + thread.length),
            role: "user",
            content: [{ type: "text", text: prompt }]
          });
          if (assistants[0]) {
            var a = assistants[0];
            thread.push({
              id: a.id || ("asst-" + thread.length),
              role: "assistant",
              model: modelOf(a, ev, "A"),
              model_source: modelOf(a, ev, "A") ? "history_metadata" : "unknown",
              model_identity_verified: false,
              model_id: a.modelId || a.model_id || ev.modelAId || null,
              content: [{ type: "text", text: asText(a.content) }]
            });
          }
        }
      } else {
        i++;
      }
    }
    var title = (meta && meta.title) || ev.title || (battles[0] && battles[0].prompt) || "";
    var mode = battles.length ? (ev.mode || "battle") : (ev.mode || "direct");
    return {
      schema_version: AE.SCHEMA_VERSION || "2.1",
      export: {
        mode: "full_history",
        exported_at: new Date().toISOString(),
        extension_version: (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.getManifest)
          ? chrome.runtime.getManifest().version : "1.18.0",
        source: {
          site: "arena.ai",
          mode: mode,
          url: "https://arena.ai/c/" + id
        }
      },
      session: {
        session_id: id,
        conversation_key: "c:" + id,
        title: title,
        started_at: ev.createdAt || (meta && meta.createdAt) || null
      },
      messages: thread,
      battles: battles,
      meta: {
        capture_sources: ["history_api"],
        completeness: "partial",
        warnings: ["Backfilled from Arena history API (unofficial). Live streams were not captured."]
      }
    };
  };

  function agentPartsToBlocks(parts) {
    var blocks = [];
    (Array.isArray(parts) ? parts : []).forEach(function (part) {
      if (!part || typeof part !== "object") return;
      var typ = String(part.type || "");
      if (typ === "text" && part.text) blocks.push({ type: "text", text: part.text });
      else if ((typ === "reasoning" || typ === "thinking") && part.text) blocks.push({ type: "thinking", text: part.text });
      else if (typ.indexOf("tool-") === 0) {
        blocks.push({
          type: "tool_call",
          tool_name: typ.replace(/^tool-/, ""),
          call_id: part.toolCallId || part.id || null,
          arguments: part.input || part.arguments || null
        });
        if (part.output != null || part.errorText != null) {
          blocks.push({
            type: "tool_result",
            tool_name: typ.replace(/^tool-/, ""),
            call_id: part.toolCallId || part.id || null,
            status: part.errorText != null ? "error" : "success",
            output: part.errorText != null ? part.errorText : part.output
          });
        }
      }
    });
    return blocks;
  }

  AE.historyAgentToPayload = function (agent, meta) {
    agent = agent || {};
    var id = AE.historyUuid(agent.id || (meta && meta.id));
    var messages = (Array.isArray(agent.messages) ? agent.messages : []).map(function (m, i) {
      return {
        id: m.id || ("msg-" + i),
        role: String(m.role || "assistant").toLowerCase(),
        content: AE.scrubSecrets(agentPartsToBlocks(m.parts)),
        metadata: AE.assistantMetadata(m)
      };
    });
    var title = (meta && meta.title) || agent.title || "";
    if (!title) {
      var u = messages.filter(function (m) { return m.role === "user"; })[0];
      if (u && u.content && u.content[0] && u.content[0].text) title = u.content[0].text.slice(0, 80);
    }
    return {
      schema_version: AE.SCHEMA_VERSION || "2.1",
      export: {
        mode: "full_history",
        exported_at: new Date().toISOString(),
        extension_version: (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.getManifest)
          ? chrome.runtime.getManifest().version : "1.18.0",
        source: {
          site: "arena.ai",
          mode: "agent",
          url: "https://arena.ai/agent/" + id
        }
      },
      session: {
        session_id: id,
        conversation_key: "c:" + id,
        title: title,
        orchestrator_model: null,
        orchestrator_model_source: "not_revealed",
        started_at: agent.createdAt || (meta && meta.createdAt) || null
      },
      messages: messages,
      battles: [],
      meta: {
        capture_sources: ["history_api"],
        transcript: AE.transcriptMetadata(agent),
        completeness: "partial",
        warnings: ["Backfilled from Arena history API (unofficial). Live streams were not captured."]
      }
    };
  };

  AE.historyRecordToPayload = function (record) {
    if (!record || typeof record !== "object") return null;
    var meta = record._historyMeta || {};
    if (record.type === "agentic" || (Array.isArray(record.messages) && record.messages.some(function (m) {
      return m && Array.isArray(m.parts);
    }))) {
      return AE.historyAgentToPayload(record, meta);
    }
    return AE.historyEvaluationToPayload(record, meta);
  };
})();

;
// Source: src/content.js
/* ISOLATED-world content script: bridges MAIN-world interceptor events into
 * the extension (service worker), and serves on-demand DOM snapshots for
 * fallback/backfill and completeness checks at export time. */
(function () {
  "use strict";
  if (window.__arenaExporterContentInstalled) return;
  window.__arenaExporterContentInstalled = true;
  try {
    window.postMessage({ type: "__ARENA_EXPORTER_REBIND__", ts: Date.now() }, location.origin || "*");
  } catch (eRebind) { /* ignore */ }

  /* Forward captured network events from the MAIN world to the service worker.
   * Same-origin page scripts can also postMessage this namespace, so we still
   * require a known event kind and the page origin; the worker then refuses
   * anything not coming from an arena.ai tab. */
  var ALLOWED_EVT_KINDS = {
    interceptor_ready: 1,
    page_context: 1,
    session_hint: 1,
    endpoint: 1,
    battle_vote: 1,
    stream_end: 1,
    stream_done: 1,
    ws: 1,
    stream_chunk: 1,
    rsc_row: 1,
    request: 1,
    request_error: 1,
    stream_error: 1,
    page_data: 1,
    sse: 1,
    json: 1,
    sse_raw: 1
  };

  window.addEventListener("message", function (ev) {
    if (ev.source !== window || !ev.data || ev.data.type !== AE.MSG_NS) return;
    if (ev.origin && ev.origin !== location.origin) return;
    if (!ev.data.evt || !ALLOWED_EVT_KINDS[ev.data.evt.kind]) return;
    try {
      chrome.runtime.sendMessage({ type: "AE_EVENT", evt: ev.data.evt }, function () {
        void chrome.runtime.lastError; // swallow "worker sleeping" races
      });
    } catch (e) { /* extension context invalidated (reload) — drop */ }
  }, false);

  /* ---------- ballot click capture ----------
   * The vote mutation is client-side and may not produce a network request.
   * Capture the semantic choice at the point of user interaction, before
   * React removes/re-renders the ballot controls. */
  var lastVoteClick = { key: "", at: 0 };

  function conversationKeyFromHref(href) {
    var m = /\/(?:c|agent)\/([A-Za-z0-9_-]+)/.exec(String(href || ""));
    return m ? "c:" + m[1] : null;
  }

  function emitPageContext() {
    try {
      chrome.runtime.sendMessage({
        type: "AE_EVENT",
        evt: {
          kind: "page_context",
          url: location.href,
          title: document.title || "",
          conversationKey: conversationKeyFromHref(location.href),
          capturedAt: new Date().toISOString()
        }
      }, function () { void chrome.runtime.lastError; });
    } catch (e) { /* extension context invalidated */ }
  }

  emitPageContext();
  var pageDataTimer = null;
  var lastPageData = "";
  function readPageData() {
    if (!AE.parsePageData) return null;
    var scripts = document.querySelectorAll("script");
    var text = "";
    for (var i = 0; i < scripts.length && text.length < 8 * 1024 * 1024; i++) {
      var script = scripts[i].textContent || "";
      if (script.indexOf("__next_f") !== -1) text += script + "\n";
    }
    return AE.parsePageData(text, location.href);
  }
  function emitPageData() {
    pageDataTimer = null;
    try {
      var data = readPageData();
      if (!data || (!data.catalog && !data.transcript)) return;
      data = AE.scrubSecrets(data);
      var key = location.href + JSON.stringify({ models: data.catalog && data.catalog.models, transcript: data.transcript });
      if (key === lastPageData) return;
      lastPageData = key;
      chrome.runtime.sendMessage({ type: "AE_EVENT", evt: { kind: "page_data", pageUrl: location.href, url: location.href, data: data } }, function () { void chrome.runtime.lastError; });
    } catch (e) { /* hydration is optional and can arrive in partial chunks */ }
  }
  function schedulePageData() {
    if (!pageDataTimer) pageDataTimer = setTimeout(emitPageData, 500);
  }
  schedulePageData();
  document.addEventListener("DOMContentLoaded", schedulePageData, { once: true });
  if (typeof MutationObserver === "function") {
    new MutationObserver(function (mutations) {
      if (mutations.some(function (m) {
        return (m.target && m.target.nodeName === "SCRIPT") || Array.prototype.some.call(m.addedNodes || [], function (n) {
          return n.nodeName === "SCRIPT" || (n.querySelector && n.querySelector("script"));
        });
      })) schedulePageData();
    }).observe(document, { childList: true, subtree: true });
  }
  var lastHref = location.href;
  setInterval(function () {
    if (location.href !== lastHref) {
      lastHref = location.href;
      emitPageContext();
      schedulePageData();
    }
  }, 1500);

  function voteControlFromEvent(ev) {
    var path = typeof ev.composedPath === "function" ? ev.composedPath() : [];
    if (!path.length) {
      var n = ev.target;
      while (n) { path.push(n); n = n.parentElement; }
    }
    return AE.dom && AE.dom.voteFromPath ? AE.dom.voteFromPath(path) : null;
  }

  function emitVote(found) {
    var now = Date.now();
    var key = found.choice + "|" + found.label;
    if (key === lastVoteClick.key && now - lastVoteClick.at < 750) return;
    lastVoteClick = { key: key, at: now };
    chrome.runtime.sendMessage({
      type: "AE_EVENT",
      evt: {
        kind: "battle_vote",
        choice: found.choice,
        label: found.label,
        source: "dom_click",
        url: location.href,
        capturedAt: new Date(now).toISOString()
      }
    }, function () { void chrome.runtime.lastError; });
  }

  /* Only real user input counts. AE.dom.expandCollapsed() fires synthetic
   * .click() on every disclosure control before each DOM snapshot, and those
   * bubble through this same listener — that is how a single export once
   * fabricated 17 "votes" in half a second. */
  function onVoteGesture(ev) {
    try {
      if (!ev.isTrusted) return;
      var found = voteControlFromEvent(ev);
      if (!found) return;
      emitVote(found);
    } catch (e) { /* never interfere with the host page */ }
  }

  document.addEventListener("click", onVoteGesture, true);
  document.addEventListener("pointerup", onVoteGesture, true);

  /* RPC from popup/background. */
  chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
    if (!msg || typeof msg.type !== "string") return;

    if (msg.type === "AE_PING") {
      sendResponse({ ok: true, url: location.href });
      return;
    }

    if (msg.type === "AE_DOM_SNAPSHOT") {
      // Expand collapsed thinking/tool panels first, then scrape.
      Promise.resolve().then(function () { return AE.dom.expandCollapsed(); }).then(function () {
        var snapshot = AE.dom.extract();
        snapshot.battle = AE.dom.battleInfo();
        snapshot.pageData = readPageData();
        return AE.scrubSecrets(snapshot);
      }).then(sendResponse, function () {
        // Always close the message channel; never return an unfiltered snapshot.
        sendResponse({ error: "Page capture failed. Let the current response finish, then reload the Arena tab." });
      });
      return true; // async response
    }

    if (msg.type === "AE_FETCH_ATTACHMENTS") {
      // Fetch artifact bytes (workspace/preview-token URLs) same-origin and
      // return data URLs so the popup can save them beside the export JSON.
      var urls = (msg.urls || []).slice(0, 50).filter(function (u) {
        return !AE.dom.isAllowedAttachmentUrl || AE.dom.isAllowedAttachmentUrl(u);
      });
      var results = [];
      var chain = Promise.resolve();
      urls.forEach(function (url, i) {
        chain = chain.then(function () {
          return AE.dom.fetchAttachment(url).then(function (r) { results[i] = r; });
        });
      });
      chain.then(function () { sendResponse({ ok: true, results: results }); });
      return true; // async response
    }

    if (msg.type === "AE_HISTORY_LIST") {
      AE.historyListAll({
        onPage: function (st) {
          try { chrome.runtime.sendMessage({ type: "AE_HISTORY_PROGRESS", stage: "list", page: st.page, count: st.count }); } catch (e) {}
        }
      }).then(function (list) {
        sendResponse({ ok: true, list: list });
      }).catch(function (err) {
        var text = String(err && err.message ? err.message : err);
        if (/HTTP 401|HTTP 403/.test(text)) text = "Not signed in on this tab — log into arena.ai, then try again.";
        sendResponse({ ok: false, error: text });
      });
      return true;
    }

    if (msg.type === "AE_HISTORY_FETCH") {
      var item = msg.item || {};
      AE.historyFetchRecord(item).then(function (rec) {
        rec._historyMeta = item;
        sendResponse({ ok: true, record: rec });
      }).catch(function (err) {
        sendResponse({ ok: false, error: String(err && err.message ? err.message : err), id: item.id });
      });
      return true;
    }

    if (msg.type === "AE_DOM_DEBUG") {
      // Selector recon dump: what the extractor found + raw container HTML.
      AE.dom.expandCollapsed().then(function () {
        var out;
        try {
          /* Redacted: this dump is meant to be shared for selector tuning, so
           * it carries DOM shape rather than the conversation itself. */
          out = { extraction: AE.dom.redact(AE.dom.extract()), debug: AE.dom.debugInfo() };
        } catch (e) {
          out = { error: String(e) };
        }
        sendResponse(out);
      });
      return true; // async response
    }
  });
})();

})();
