// Generated by tools/build-release.mjs. Edit the source modules.
(function () {
// Source: src/lib/schema.js
/* Shared constants for Arena Agent Exporter.
 * Loaded by both the content-script world (as a classic script) and the
 * service worker (via importScripts). Everything hangs off the global `AE`. */
var AE = AE || {};

AE.SCHEMA_VERSION = "2.1";

/* postMessage bridge type between MAIN-world interceptor and ISOLATED content script */
AE.MSG_NS = "__ARENA_EXPORTER_EVT__";

/* Canonical block types used in the export schema */
AE.BLOCK_TYPES = [
  "thinking",    // chain-of-thought text
  "text",        // visible message text (markdown)
  "tool_call",   // tool invocation with arguments
  "tool_result", // output of a tool invocation
  "command",     // shell/terminal command + output
  "action",      // higher-level agent action (create_file, navigate, ...)
  "artifact"     // produced files / images / reports
];

AE.ROLES = ["user", "assistant", "system", "tool"];

/* Canonical battle-vote choices. A/B identify a single preferred lane;
 * both_good and neither_good preserve the two non-singular ballot outcomes. */
AE.BATTLE_VOTE_CHOICES = ["A", "B", "both_good", "neither_good"];

AE.isPlaceholderModel = function (name) {
  var t = String(name == null ? "" : name).replace(/\s+/g, " ").trim();
  if (!t) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(t)) return true;
  return /^(?:response|model|assistant|lane|player|option)\s*[ab](?:\s+[ab]\s+is\s+better)?$/i.test(t);
};

;
// Source: src/lib/privacy.js
/* Credential filtering shared by capture, history and export.
 * Redaction is structural first: nested objects, JSON-in-JSON strings and URLs
 * are traversed before bounded diagnostic samples are stored. */
var AE = AE || {};
(function () {
  "use strict";

  var SECRET_NAMES = /^(?:recaptcha.*|grecaptcha.*|captcha.*|authorization|proxyauthorization|cookie|setcookie|apikey|xapikey|secret|clientsecret|password|passwd|token|accesstoken|publicaccesstoken|refreshtoken|idtoken|sessiontoken|authtoken|bearertoken|oauthtoken|oauth2token|githubtoken|personalaccesstoken|pat|jwt|credentials|privatekey)$/i;
  function normalizedName(name) { return String(name || "").replace(/[^a-z0-9]/gi, ""); }
  function secretName(name) { return SECRET_NAMES.test(normalizedName(name)); }

  var FIELD = "(?:recaptcha[a-z0-9_-]*|g-recaptcha[a-z0-9_-]*|captcha[a-z0-9_-]*|authorization|proxy-authorization|cookie|set-cookie|api[-_]?key|x[-_]?api[-_]?key|client[-_]?secret|secret|password|passwd|(?:public[-_]?)?access[-_]?token|refresh[-_]?token|id[-_]?token|session[-_]?token|auth[-_]?token|bearer[-_]?token|oauth2?[-_]?token|github[-_]?token|personal[-_]?access[-_]?token|token|jwt|credentials|private[-_]?key)";
  var FIELD_VALUE = new RegExp("((?:[\\\"']?" + FIELD + "[\\\"']?)\\s*[:=]\\s*)(?:\\\"(?:\\\\.|[^\\\"\\\\])*(?:\\\"|$)|'(?:\\\\.|[^'\\\\])*(?:'|$)|[^&\\s,;}\\]]+)", "gi");
  var QUERY_SECRET = new RegExp("([?&]" + FIELD + "=)[^&#\\s]*", "gi");
  var PEM_PRIVATE = /-----BEGIN (?:[A-Z0-9 ]+ )?PRIVATE KEY-----[\s\S]*?-----END (?:[A-Z0-9 ]+ )?PRIVATE KEY-----/g;
  var OPENSSH_PRIVATE = /-----BEGIN OPENSSH PRIVATE KEY-----[\s\S]*?-----END OPENSSH PRIVATE KEY-----/g;

  function scrubFragment(url) {
    var hash = String(url.hash || "");
    if (!hash || hash.indexOf("=") === -1) return false;
    try {
      var params = new URLSearchParams(hash.slice(1));
      var changed = false;
      Array.from(params.keys()).forEach(function (key) {
        if (!secretName(key)) return;
        params.set(key, "[REDACTED]");
        changed = true;
      });
      if (changed) url.hash = "#" + params.toString();
      return changed;
    } catch (_) { return false; }
  }

  AE.scrubCredentialUrl = function (value) {
    var text = String(value || "");
    try {
      var url = new URL(text), changed = false;
      if (url.username || url.password) {
        url.username = "";
        url.password = "";
        changed = true;
      }
      Array.from(url.searchParams.keys()).forEach(function (key) {
        if (!secretName(key)) return;
        url.searchParams.set(key, "[REDACTED]");
        changed = true;
      });
      if (scrubFragment(url)) changed = true;
      // Exact preservation matters for raw stream grammars: harmless URLs must
      // remain byte-for-byte unchanged or a citation/tool frame can stop parsing.
      return changed ? url.toString() : text;
    } catch (_) {
      return text.replace(QUERY_SECRET, "$1[REDACTED]");
    }
  };

  function scrubEmbeddedUrls(text) {
    return String(text || "").replace(/\bhttps?:\/\/[^\s<>"']+/gi, function (candidate) {
      var trailing = "";
      while (/[),.;\]}]$/.test(candidate)) {
        trailing = candidate.slice(-1) + trailing;
        candidate = candidate.slice(0, -1);
      }
      return AE.scrubCredentialUrl(candidate) + trailing;
    });
  }

  AE.redactSecretText = function (text) {
    var redacted = String(text || "")
      .replace(PEM_PRIVATE, "[REDACTED_PRIVATE_KEY]")
      .replace(OPENSSH_PRIVATE, "[REDACTED_PRIVATE_KEY]")
      .replace(/\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]*)?/g, "[REDACTED_JWT]")
      .replace(/\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+\/_-]+=*/gi, "[REDACTED_AUTH]")
      .replace(/\b(?:github_pat_|gh[pousr]_)[A-Za-z0-9_]{12,}/gi, "[REDACTED_GITHUB_TOKEN]")
      .replace(/\bsk-[A-Za-z0-9_-]{16,}/g, "[REDACTED_KEY]")
      .replace(/^((?:proxy-)?authorization|cookie|set-cookie)(\s*:\s*)[^\r\n]*/gim, "$1$2[REDACTED]")
      .replace(QUERY_SECRET, "$1[REDACTED]")
      .replace(FIELD_VALUE, '$1"[REDACTED]"');
    return scrubEmbeddedUrls(redacted);
  };

  AE.scrubSecrets = function (value) {
    function walk(v, depth) {
      if (typeof v === "string") {
        // Trigger records and websocket frames often contain JSON inside JSON.
        if (depth < 16 && /^[\s]*[\[{]/.test(v)) {
          try { return JSON.stringify(walk(JSON.parse(v), depth + 1)); } catch (e) { /* raw or truncated frame */ }
        }
        return AE.redactSecretText(v);
      }
      if (Array.isArray(v)) {
        if (v.length === 2 && typeof v[0] === "string" && secretName(v[0])) return [v[0], "[REDACTED]"];
        return v.map(function (item) { return walk(item, depth + 1); });
      }
      if (!v || typeof v !== "object") return v;
      var out = {};
      Object.keys(v).forEach(function (key) {
        if (secretName(key) || key === "__proto__" || key === "constructor" || key === "prototype") return;
        out[key] = walk(v[key], depth + 1);
      });
      return out;
    }
    return walk(value, 0);
  };

  AE.safeTransportHeaders = function (headers) {
    var out = {};
    ["x-session-settled", "x-stream-version", "x-arena-chat-id"].forEach(function (name) {
      var value = null;
      if (headers && typeof headers.get === "function") value = headers.get(name);
      else if (Array.isArray(headers)) headers.forEach(function (pair) {
        if (pair && String(pair[0]).toLowerCase() === name) value = pair[1];
      });
      else if (headers) Object.keys(headers).forEach(function (key) {
        if (key.toLowerCase() === name) value = headers[key];
      });
      if (value != null) out[name] = AE.redactSecretText(value).slice(0, 200);
    });
    return out;
  };
})();

;
// Source: src/lib/page-data.js
/* Read public page hydration data without executing scripts or depending on
 * bundle module ids. Catalog labels describe a selection, not a hidden Agent model. */
var AE = AE || {};
(function () {
  "use strict";
  AE.catalogModelLabel = function (row) {
    if (!row || typeof row !== "object") return null;
    var values = [row.publicName, row.displayName, row.name];
    for (var i = 0; i < values.length; i++) {
      if (typeof values[i] === "string" && values[i] && !AE.isPlaceholderModel(values[i])) return values[i];
    }
    return null;
  };
  AE.catalogModel = function (catalog, id) {
    if (!id || !catalog || !Array.isArray(catalog.models)) return null;
    return catalog.models.find(function (row) { return row.id === id; }) || null;
  };
  AE.cleanModelCatalog = function (rows, url) {
    var seen = {};
    var fields = ["id", "name", "publicName", "displayName", "organization", "provider", "userSelectable", "rank", "rankByModality"];
    var models = [];
    (Array.isArray(rows) ? rows : []).slice(0, 4000).forEach(function (row) {
      if (!row || typeof row.id !== "string" || row.id.length > 160 || seen[row.id]) return;
      seen[row.id] = true;
      var clean = {};
      fields.forEach(function (field) {
        var value = row[field];
        if (value == null) return;
        if (typeof value === "string") clean[field] = value.slice(0, 300);
        else if (typeof value === "number" || typeof value === "boolean") clean[field] = value;
        else if (typeof value === "object" && JSON.stringify(value).length < 3000) clean[field] = value;
      });
      models.push(clean);
    });
    return { source_url: url || null, captured_at: new Date().toISOString(), models: models };
  };
  AE.assistantMetadata = function (message) {
    var source = Object.assign({}, message || {}, (message && (message.metadata || message.messageMetadata)) || {});
    var out = {};
    ["nodeId", "manifestNodeId", "pending", "requiresReview", "feedback"].forEach(function (key) {
      if (Object.prototype.hasOwnProperty.call(source, key)) out[key] = source[key];
    });
    return AE.scrubSecrets(out);
  };
  AE.transcriptMetadata = function (transcript) {
    var out = {};
    ["pagination", "transcriptReadStrategy", "productMode", "feedbackType", "customFeedbackArm"].forEach(function (key) {
      if (Object.prototype.hasOwnProperty.call(transcript || {}, key)) out[key] = transcript[key];
    });
    if (transcript && transcript.session) out.session = AE.scrubSecrets(transcript.session);
    return AE.scrubSecrets(out);
  };
  AE.pageDataFromObjects = function (objects, url, references) {
    var result = { catalog: null, transcript: null };
    var visits = 0;
    var visited = new Set();
    function resolve(value, depth) {
      if (depth > 12) return value;
      if (typeof value === "string" && /^\$[a-f0-9]+$/i.test(value) && references) {
        var ref = references[value.slice(1)];
        if (ref !== undefined && ref !== value) return resolve(ref, depth + 1);
      }
      if (Array.isArray(value)) return value.map(function (v) { return resolve(v, depth + 1); });
      return value;
    }
    function walk(value, depth) {
      if (++visits > 80000 || depth > 35) return;
      value = resolve(value, 0);
      if (!value || typeof value !== "object" || visited.has(value)) return;
      visited.add(value);
      if (value.initialModels) {
        var rows = resolve(value.initialModels, 0);
        if (Array.isArray(rows)) result.catalog = AE.cleanModelCatalog(rows, url);
      }
      var messages = resolve(value.messages, 0);
      if (Array.isArray(messages) && messages.some(function (m) { return m && m.role && Array.isArray(m.parts); })) {
        result.transcript = Object.assign({}, value, { messages: messages });
      }
      Object.keys(value).forEach(function (key) {
        if (key !== "initialModels" && key !== "messages") walk(value[key], depth + 1);
      });
    }
    (Array.isArray(objects) ? objects : [objects]).forEach(function (o) { walk(o, 0); });
    return result;
  };
  AE.parsePageData = function (source, url) {
    source = String(source || "").slice(0, 8 * 1024 * 1024);
    var chunks = [];
    var re = /self\.__next_f\.push\(\s*\[\s*1\s*,\s*("(?:\\.|[^"\\])*")\s*\]\s*\)/g;
    var match;
    while ((match = re.exec(source))) {
      try { chunks.push(JSON.parse(match[1])); } catch (e) { /* incomplete script */ }
    }
    var flight = chunks.length ? chunks.join("") : source;
    var objects = [], references = {};
    flight.split(/\r?\n/).forEach(function (line) {
      var row = /^([a-f0-9]+):(?:J)?([\[{].*)$/i.exec(line);
      if (!row) return;
      try {
        references[row[1]] = JSON.parse(row[2]);
        objects.push(references[row[1]]);
      } catch (e) { /* non-JSON Flight row or a partial stream */ }
    });
    if (!objects.length) {
      try { objects.push(JSON.parse(flight)); } catch (e) { /* HTML without hydration data */ }
    }
    return AE.pageDataFromObjects(objects, url, references);
  };
})();

;
// Source: src/interceptor.js
/* MAIN-world interceptor — injected at document_start BEFORE arena.ai's
 * bundle loads. Hooks fetch() and XMLHttpRequest to observe every API
 * response (JSON and SSE streams) without disturbing the app's own reads,
 * then forwards captured payloads to the ISOLATED content script via
 * postMessage. This is the primary capture channel: network payloads carry
 * the full thinking/tool trace that the DOM may render collapsed or
 * truncated. */
(function () {
  "use strict";
  var NS = "__ARENA_EXPORTER_EVT__";

  function pingReady() {
    try {
      var target = "*";
      try { if (location.origin) target = location.origin; } catch (e0) { /* ignore */ }
      window.postMessage({ type: NS, evt: { kind: "interceptor_ready", url: location.href } }, target);
    } catch (e1) { /* never break the host page */ }
  }

  window.addEventListener("message", function (ev) {
    if (ev.source !== window || !ev.data || ev.data.type !== "__ARENA_EXPORTER_REBIND__") return;
    pingReady();
  });

  if (window.__arenaExporterInstalled) {
    pingReady();
    return;
  }
  window.__arenaExporterInstalled = true;

  /* Agent Mode recon findings:
   *  - /ai-proxy/realtime/v1/sessions/<uuid>/out  → long-lived agent event stream
   *  - /api/chat/<uuid>/...                       → chat-scoped REST endpoints
   * The /out stream framing is sniffed at runtime (SSE vs NDJSON vs raw). */
  var REALTIME_OUT_RE = /\/realtime\/v[0-9]+\/sessions\/([0-9a-fA-F-]{8,})\/out/i;
  var CHAT_ID_RE = /\/api\/chat\/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})/i;
  /* User prompts enter via .../sessions/<id>/in/append (POST body) — request
   * bodies on these endpoints are captured, not just responses. */
  var RELEVANT_REQ_RE = /(in\/append|create-chat|create-evaluation|post-to-evaluation|\/nextjs-api\/)/i;
  var EVALUATION_STREAM_RE = /(create-evaluation|post-to-evaluation)/i;
  /* Skip telemetry/assets. Only these URLs are forwarded to the SW. */
  var CAPTURE_URL_RE = /(\/realtime\/v[0-9]+\/sessions\/|\/in\/append|\/api\/chat\/|create-chat|create-evaluation|post-to-evaluation|workspace|\/api\/history|\/text\/(direct|side-by-side)|\/max(?:[/?#]|$)|\/agent\/)/i;
  var EVAL_EMIT_CHUNK = 8192;

  /* Third-party telemetry (Datadog RUM beacons and friends) was reaching the
   * archive. Nothing outside arena.ai / lmarena.ai (legacy host that 301s) is
   * ever interesting here. Code-preview hosts such as arena.site are not
   * hooked — the interceptor only observes same-site Arena API traffic. */
  function isArenaUrl(url) {
    try {
      return /^([a-z0-9-]+\.)*(arena\.ai|lmarena\.ai)$/i.test(new URL(String(url), location.href).hostname);
    } catch (e) {
      return false;
    }
  }

  function isCaptureUrl(url) {
    url = String(url || "");
    if (!isArenaUrl(url)) return false;
    return REALTIME_OUT_RE.test(url) || EVALUATION_STREAM_RE.test(url) || CAPTURE_URL_RE.test(url);
  }

  var requestSequence = 0;
  function contextFor(method) {
    return { requestId: "ae-" + Date.now().toString(36) + "-" + (++requestSequence) + "-" + Math.random().toString(36).slice(2, 8),
      method: String(method || "GET").toUpperCase(), pageUrl: location.href, capturedAt: new Date().toISOString() };
  }
  function safeText(value) {
    return typeof AE !== "undefined" && AE.scrubSecrets ? AE.scrubSecrets(String(value || "")) : String(value || "");
  }
  function emit(evt, context) {
    try {
      evt = Object.assign({ pageUrl: location.href }, context || {}, evt);
      if (typeof AE !== "undefined" && AE.scrubSecrets) evt = AE.scrubSecrets(evt);
      var target = "*";
      try { if (location.origin) target = location.origin; } catch (e) { /* ignore */ }
      window.postMessage({ type: NS, evt: evt }, target);
    } catch (e) { /* never break the host page */ }
  }

  /* ---------- stream consumption (SSE / NDJSON / raw sniffing) ---------- */

  function parseSSEFrame(url, frame, context) {
    var event = "message";
    var dataLines = [];
    var lines = frame.split(/\r\n|\r|\n/);
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      if (line.indexOf("event:") === 0) event = line.slice(6).trim();
      else if (line.indexOf("data:") === 0) dataLines.push(line.slice(5).replace(/^ /, ""));
    }
    if (!dataLines.length) return;
    var data = dataLines.join("\n");
    if (data === "[DONE]") { emit({ kind: "stream_done", url: url }, context); return; }
    try {
      emit({ kind: "sse", url: url, event: event, data: JSON.parse(data) }, context);
    } catch (e) {
      if (data.trim()) emit({ kind: "sse_raw", url: url, event: event, text: safeText(data).slice(0, 2000) }, context);
    }
  }

  function parseNDJSONLine(url, line, context) {
    if (!line) return;
    try {
      emit({ kind: "json", url: url, data: JSON.parse(line) }, context);
    } catch (e) {
      emit({ kind: "stream_chunk", url: url, text: safeText(line).slice(0, 2048) }, context);
    }
  }

  var SSE_FRAME_RE = /^\s*(event:|data:|id:|retry:|:)/;
  /* Next.js RSC / flight rows look like "<rowid>:<payload>" (e.g. the
   * evaluation battle stream emits "a2:[{\"type\":\"heartbeat\"}]"). */
  var RSC_LINE_RE = /^\s*[0-9a-zA-Z]+:/;

  function sniffStreamMode(buf) {
    if (SSE_FRAME_RE.test(buf)) return "sse";
    if (/^\s*[\{\[]/.test(buf)) return "ndjson";
    if (RSC_LINE_RE.test(buf)) return "rsc";
    // The first read can contain only "da" from "data:" or part of a row id.
    return buf.length < 64 && !/[\r\n]/.test(buf) ? null : "raw";
  }

  function parseRSCLine(url, line, context) {
    if (!line) return;
    var ci = line.indexOf(":");
    var rowId = ci > 0 ? line.slice(0, ci) : null;
    var rest = ci > 0 ? line.slice(ci + 1) : line;
    var data = null;
    try { data = JSON.parse(rest); } catch (e) { /* keep null */ }
    emit({ kind: "rsc_row", url: url, rowId: rowId, data: data, text: safeText(line).slice(0, 4096) }, context);
  }

  /* Battle evaluation bodies are a JSON init record concatenated with
   * delimiter-free lane deltas (`}a0:"…"b0:"…"`). That is not NDJSON —
   * never JSON.parse line-by-line and never truncate to 2KB. */
  async function consumeEvalStream(url, res, context) {
    var reader = res.body.getReader();
    var dec = new TextDecoder();
    var carry = "";
    try { for (;;) {
      var r = await reader.read();
      if (r.done) break;
      carry += dec.decode(r.value, { stream: true });
      while (carry.length >= EVAL_EMIT_CHUNK) {
        emit({ kind: "stream_chunk", url: url, text: carry.slice(0, EVAL_EMIT_CHUNK) }, context);
        carry = carry.slice(EVAL_EMIT_CHUNK);
      }
    } } catch (err) {
      if (carry) emit({ kind: "stream_chunk", url: url, text: carry }, context);
      throw err;
    } finally { if (reader.releaseLock) reader.releaseLock(); }
    try { carry += dec.decode(); } catch (e) { /* ignore */ }
    if (carry) emit({ kind: "stream_chunk", url: url, text: carry }, context);
    emit({ kind: "stream_end", url: url }, context);
  }

  async function consumeStream(url, res, context, contentType) {
    var reader = res.body.getReader();
    var dec = new TextDecoder();
    var buf = "";
    var mode = /text\/event-stream/i.test(contentType || "") ? "sse" : null;
    var pendingCR = false;
    function decodeChunk(bytes, done) {
      var text = bytes ? dec.decode(bytes, { stream: true }) : dec.decode();
      if (pendingCR) { text = "\r" + text; pendingCR = false; }
      if (!done && text.endsWith("\r")) { pendingCR = true; text = text.slice(0, -1); }
      return text.replace(/\r\n?/g, "\n");
    }
    try {
    for (;;) {
      var r = await reader.read();
      buf += decodeChunk(r.value, r.done);
      if (r.done) break;
      if (!mode) mode = sniffStreamMode(buf);
      if (mode === "sse") {
        var idx;
        while ((idx = buf.indexOf("\n\n")) !== -1) {
          parseSSEFrame(url, buf.slice(0, idx), context);
          buf = buf.slice(idx + 2);
        }
      } else if (mode === "ndjson") {
        var nl;
        while ((nl = buf.indexOf("\n")) !== -1) {
          var line = buf.slice(0, nl).trim();
          buf = buf.slice(nl + 1);
          parseNDJSONLine(url, line, context);
        }
      } else if (mode === "rsc") {
        var nl;
        while ((nl = buf.indexOf("\n")) !== -1) {
          var line = buf.slice(0, nl).trim();
          buf = buf.slice(nl + 1);
          parseRSCLine(url, line, context);
        }
      } else if (mode === "raw" && buf.length > 2048) {
        emit({ kind: "stream_chunk", url: url, text: safeText(buf.slice(0, 2048)) }, context);
        buf = buf.slice(2048);
      }
      if (buf.length > 4 * 1024 * 1024) {
        if (reader.cancel) reader.cancel().catch(function () {});
        throw new Error("Stream frame exceeded the 4 MiB capture limit");
      }
    }
    if (buf.trim()) {
      if (mode === "sse") parseSSEFrame(url, buf, context);
      else if (mode === "ndjson") parseNDJSONLine(url, buf.trim(), context);
      else if (mode === "rsc") parseRSCLine(url, buf.trim(), context);
      else emit({ kind: "stream_chunk", url: url, text: safeText(buf).slice(0, 2048) }, context);
    }
    emit({ kind: "stream_end", url: url }, context);
    } finally { if (reader.releaseLock) reader.releaseLock(); }
  }

  /* ---------- response dispatch ---------- */

  function emitSessionHint(url, context) {
    var m = REALTIME_OUT_RE.exec(url) || CHAT_ID_RE.exec(url);
    if (m) emit({ kind: "session_hint", sessionId: m[1], url: url }, context);
  }

  function handleResponse(url, res, context) {
    if (!isCaptureUrl(url)) return;
    var ct = "";
    try { ct = (res.headers.get("content-type") || "").toLowerCase(); } catch (e) {}
    var headers = typeof AE !== "undefined" && AE.safeTransportHeaders ? AE.safeTransportHeaders(res.headers) : {};
    emit({ kind: "endpoint", url: url, status: res.status, contentType: ct, headers: headers }, context);
    if (res.status >= 400) {
      res.clone().text().then(function (text) {
        emit({ kind: "request_error", url: url, status: res.status, error: safeText(text).slice(0, 4000) }, context);
      }).catch(function (err) { emit({ kind: "request_error", url: url, status: res.status, error: String(err.message || err) }, context); });
      return;
    }
    emitSessionHint(url, context);
    function streamError(err) { emit({ kind: "stream_error", url: url, error: String(err.message || err), aborted: err.name === "AbortError" }, context); }
    try {
      var isRealtimeOut = REALTIME_OUT_RE.test(url);
      var isEvaluationStream = EVALUATION_STREAM_RE.test(url);
      if (isEvaluationStream) {
        consumeEvalStream(url, res.clone(), context).catch(streamError);
      } else if (ct.indexOf("text/event-stream") !== -1 || ct.indexOf("text/x-component") !== -1 || isRealtimeOut) {
        consumeStream(url, res.clone(), context, ct).catch(streamError);
      } else if (ct.indexOf("text/html") !== -1 && typeof AE !== "undefined" && AE.parsePageData) {
        res.clone().text().then(function (text) {
          emit({ kind: "page_data", url: url, data: AE.parsePageData(text, url) }, context);
        }).catch(streamError);
      } else if (ct.indexOf("application/json") !== -1) {
        res.clone().text().then(function (text) {
          if (!text) return;
          try {
            emit({ kind: "json", url: url, data: JSON.parse(text) }, context);
          } catch (e) { /* non-JSON despite content-type */ }
        }).catch(function () {});
      }
    } catch (e) { /* ignore */ }
  }

  /* ---------- fetch hook ---------- */

  function bodyText(body) {
    if (body == null) return "";
    if (typeof body === "string") return body;
    try {
      if (typeof URLSearchParams !== "undefined" && body instanceof URLSearchParams) return body.toString();
    } catch (e) { /* ignore */ }
    if (body && typeof body === "object") {
      try { return JSON.stringify(body); } catch (e) { /* FormData/stream — no sync representation */ }
    }
    return "";
  }

  function emitRequestCapture(url, method, body, context) {
    emit({
      kind: "request",
      url: url,
      method: String(method || "GET").toUpperCase(),
      body: safeText(body).slice(0, 200000)
    }, context);
  }

  var origFetch = window.fetch;
  window.fetch = function (input, init) {
    var url = "";
    var method = "GET";
    try {
      url = typeof input === "string" ? input : (input && input.url) || "";
      method = (init && init.method) || (typeof input === "object" && input && input.method) || "GET";
    } catch (e) {}
    var context = contextFor(method);
    try {
      if (RELEVANT_REQ_RE.test(url) && isArenaUrl(url)) {
        var hasInitBody = !!(init && init.body != null);
        if (hasInitBody) {
          emitRequestCapture(url, method, bodyText(init.body), context);
        } else if (input && typeof input.clone === "function") {
          // A common pattern is fetch(new Request(url, {body: ...})). Reading a
          // clone keeps the page's original Request body untouched.
          try {
            input.clone().text().then(function (text) {
              emitRequestCapture(url, method, text, context);
            }).catch(function () {
              emitRequestCapture(url, method, "", context);
            });
          } catch (e) {
            emitRequestCapture(url, method, "", context);
          }
        } else {
          emitRequestCapture(url, method, "", context);
        }
      }
    } catch (e) { /* ignore */ }
    var p = origFetch.apply(this, arguments);
    p.then(function (res) {
      try { handleResponse(url, res, context); } catch (e) {}
    }, function (err) {
      if (isCaptureUrl(url)) emit({ kind: "request_error", url: url, error: String(err.message || err) }, context);
    });
    return p;
  };

  /* ---------- XHR hook ---------- */

  var XP = XMLHttpRequest.prototype;
  var origOpen = XP.open;
  var origSend = XP.send;

  XP.open = function (method, url) {
    try { this.__aeUrl = String(url); this.__aeMethod = String(method); } catch (e) {}
    return origOpen.apply(this, arguments);
  };

  XP.send = function (payload) {
    var xhr = this;
    var context = contextFor(xhr.__aeMethod);
    try {
      if (RELEVANT_REQ_RE.test(xhr.__aeUrl || "") && isArenaUrl(xhr.__aeUrl || "")) {
        var xhrBody = null;
        if (typeof payload === "string") xhrBody = payload;
        else if (payload && typeof payload === "object") { try { xhrBody = JSON.stringify(payload); } catch (e) {} }
        emitRequestCapture(xhr.__aeUrl, xhr.__aeMethod || "POST", xhrBody, context);
      }
    } catch (e) { /* ignore */ }
    try {
      xhr.addEventListener("load", function () {
        try {
          var url = xhr.__aeUrl || "";
          if (!isCaptureUrl(url)) return;
          var ct = (xhr.getResponseHeader("content-type") || "").toLowerCase();
          var headers = {};
          ["x-session-settled", "x-stream-version", "x-arena-chat-id"].forEach(function (name) { var v = xhr.getResponseHeader(name); if (v) headers[name] = v; });
          emit({ kind: "endpoint", url: url, status: xhr.status, contentType: ct, headers: headers }, context);
          if (xhr.status >= 400) {
            emit({ kind: "request_error", url: url, status: xhr.status, error: safeText(xhr.responseText).slice(0, 4000) }, context);
            return;
          }
          if (ct.indexOf("application/json") !== -1 && xhr.responseText) {
            try {
              emit({ kind: "json", url: url, data: JSON.parse(xhr.responseText) }, context);
            } catch (e) { /* ignore */ }
          } else if (ct.indexOf("text/event-stream") !== -1 && xhr.responseText) {
            xhr.responseText.replace(/\r\n?/g, "\n").split(/\n\n/).forEach(function (frame) { parseSSEFrame(url, frame, context); });
            emit({ kind: "stream_end", url: url }, context);
          } else if (EVALUATION_STREAM_RE.test(url) && xhr.responseText) {
            emit({ kind: "stream_chunk", url: url, text: xhr.responseText }, context);
            emit({ kind: "stream_end", url: url }, context);
          }
        } catch (e) { /* ignore */ }
      });
      ["error", "abort"].forEach(function (name) {
        xhr.addEventListener(name, function () {
          if (isCaptureUrl(xhr.__aeUrl)) emit({ kind: "request_error", url: xhr.__aeUrl, error: "XHR " + name }, context);
        });
      });
    } catch (e) { /* ignore */ }
    return origSend.apply(this, arguments);
  };

  /* ---------- sendBeacon hook (some vote/telemetry calls use beacons) ---- */

  if (navigator.sendBeacon) {
    var origBeacon = navigator.sendBeacon.bind(navigator);
    navigator.sendBeacon = function (url, data) {
      try {
        if (isCaptureUrl(url)) {
          emitRequestCapture(String(url), "BEACON", bodyText(data), contextFor("BEACON"));
        }
      } catch (e) { /* ignore */ }
      return origBeacon(url, data);
    };
  }

  /* ---------- WebSocket hook (insurance: if realtime ever moves to WS) ---- */

  var OrigWS = window.WebSocket;
  if (OrigWS) {
    function HookedWS(url, protocols) {
      var ws = protocols !== undefined ? new OrigWS(url, protocols) : new OrigWS(url);
      var context = contextFor("WS");
      try {
        ws.addEventListener("message", function (ev) {
          try {
            if (typeof ev.data === "string" && isCaptureUrl(url)) {
              emit({ kind: "ws", url: String(url), text: ev.data }, context);
            }
          } catch (e) { /* ignore */ }
        });
      } catch (e) { /* ignore */ }
      return ws;
    }
    HookedWS.prototype = OrigWS.prototype;
    HookedWS.CONNECTING = OrigWS.CONNECTING;
    HookedWS.OPEN = OrigWS.OPEN;
    HookedWS.CLOSING = OrigWS.CLOSING;
    HookedWS.CLOSED = OrigWS.CLOSED;
    window.WebSocket = HookedWS;
  }

  emit({ kind: "interceptor_ready", url: location.href });
})();

})();
